DROP PROGRAM 01_meds_pharm_mpage:group1 GO
CREATE PROGRAM 01_meds_pharm_mpage:group1
PROMPT "Output to File/Printer/MINE" = "MINE", "User Id" = 0, "Patient ID" = 0, "Encounter Id" = 0
WITH OUTDEV, user_id, pid, eid

SET _memory_reply_string = BUILD2(
    ~<!DOCTYPE html>~,
    ~<html><head>~,
    ~<meta charset='utf-8'/>~,
    ~<meta name='discern' content='XMLCCLREQUEST,APPLINK,CCLLINK'/>~,
    ~<title>Pharmacy SPA Prototype</title>~,
    ~<style>~,
    ~* { box-sizing: border-box; }~,
    ~body { margin: 0; min-height: 100vh; font-family: Segoe UI, Arial, sans-serif; background: #f4f7fa; color: #1c2733; }~,
    ~.nav-bar { display: flex; gap: 4px; padding: 10px 12px 0; background: linear-gradient(135deg, #0c4663 0%, #155e75 100%); }~,
    ~.nav-btn { border: 0; border-radius: 10px 10px 0 0; padding: 12px 18px; background: transparent; color: #cfe4ec; cursor: pointer; font-size: 13px; font-weight: 600; }~,
    ~.nav-btn:hover { color: #ffffff; background: rgba(255,255,255,0.08); }~,
    ~.nav-btn.active { background: #f4f7fa; color: #0c4663; }~,
    ~.status-banner { min-height: 22px; padding: 10px 16px 0; font-size: 13px; }~,
    ~.status-banner.error { color: #a12622; }~,
    ~.status-banner.info { color: #155e75; }~,
    ~#app-root { padding: 16px; }~,
    ~.panel { background: #ffffff; border: 1px solid #d9e2ec; border-radius: 14px; box-shadow: 0 8px 24px rgba(18, 38, 63, 0.08); overflow: hidden; }~,
    ~.panel-head { display: flex; justify-content: space-between; align-items: center; gap: 16px; padding: 18px 20px; border-bottom: 1px solid #e6edf3; }~,
    ~.panel-head h2 { margin: 0 0 4px; font-size: 20px; }~,
    ~.panel-head p { margin: 0; color: #5d6b79; }~,
    ~.panel-body { padding: 20px; }~,
    ~.pill { display: inline-flex; align-items: center; justify-content: center; min-width: 52px; padding: 8px 12px; border-radius: 999px; background: #e8f3f8; color: #0c4663; font-size: 12px; font-weight: 700; }~,
    ~.empty-state { padding: 28px; text-align: center; color: #5d6b79; }~,
    ~.loading { display: flex; align-items: center; gap: 12px; padding: 24px; }~,
    ~.loading-spinner { width: 28px; height: 28px; border: 4px solid #d7e6ef; border-top-color: #0c7aa6; border-radius: 50%; animation: spin 0.9s linear infinite; }~,
    ~.summary-row { display: flex; gap: 12px; flex-wrap: wrap; margin-bottom: 16px; }~,
    ~.summary-card { min-width: 150px; padding: 14px 16px; border: 1px solid #d9e2ec; border-radius: 12px; background: #f8fbfd; }~,
    ~.summary-card strong { display: block; font-size: 12px; color: #5d6b79; margin-bottom: 6px; text-transform: uppercase; letter-spacing: 0.04em; }~,
    ~.summary-card span { font-size: 18px; font-weight: 700; color: #1c2733; }~,
    ~.card-grid { display: grid; gap: 14px; }~,
    ~.doc-card { border: 1px solid #d9e2ec; border-radius: 12px; padding: 14px 16px; background: #f8fbfd; }~,
    ~.doc-card h3 { margin: 0 0 6px; font-size: 16px; }~,
    ~.meta-line { color: #5d6b79; font-size: 12px; margin-bottom: 10px; }~,
    ~.note-text { white-space: pre-wrap; font-family: Segoe UI, Arial, sans-serif; font-size: 13px; line-height: 1.45; }~,
    ~table.data-grid { width: 100%; border-collapse: collapse; }~,
    ~table.data-grid th, table.data-grid td { padding: 12px 14px; border-bottom: 1px solid #e6edf3; vertical-align: top; text-align: left; }~,
    ~table.data-grid th { font-size: 12px; text-transform: uppercase; letter-spacing: 0.04em; color: #5d6b79; background: #f8fbfd; }~,
    ~table.data-grid tr:last-child td { border-bottom: 0; }~,
    ~.cat-badge { display: inline-flex; align-items: center; justify-content: center; min-width: 74px; padding: 6px 10px; border-radius: 999px; font-size: 12px; font-weight: 700; color: #14303f; }~,
    ~.scan-input { width: 120px; margin-right: 8px; padding: 8px 10px; border: 1px solid #b7c6d3; border-radius: 8px; font-size: 12px; }~,
    ~.print-btn, .link-btn { padding: 8px 12px; border: 1px solid #0c7aa6; border-radius: 8px; background: #0c7aa6; color: #ffffff; cursor: pointer; font-weight: 600; }~,
    ~.link-btn.secondary { background: #ffffff; color: #0c7aa6; }~,
    ~.print-hint { margin-top: 6px; font-size: 12px; color: #5d6b79; }~,
    ~.debug { margin: 0; padding: 20px; background: #0f1720; color: #d5dde5; overflow: auto; font-size: 12px; }~,
    ~.micro-meta { margin-bottom: 16px; color: #5d6b79; font-size: 13px; }~,
    ~.micro-scroll { overflow: auto; border: 1px solid #d9e2ec; border-radius: 12px; background: #ffffff; }~,
    ~.micro-grid { width: 100%; border-collapse: separate; border-spacing: 0; min-width: 920px; }~,
    ~.micro-grid th, .micro-grid td { border-bottom: 1px solid #e6edf3; padding: 10px 12px; vertical-align: top; text-align: left; }~,
    ~.micro-grid th { font-size: 12px; color: #5d6b79; text-transform: uppercase; letter-spacing: 0.04em; background: #f8fbfd; }~,
    ~.micro-strip { display: flex; gap: 2px; align-items: flex-start; min-width: max-content; padding: 2px 0; }~,
    ~.micro-tick, .micro-cell { width: 16px; min-width: 16px; height: 16px; border-radius: 4px; border: 1px solid #c8d4de; display: inline-flex; align-items: center; justify-content: center; font-size: 10px; line-height: 1; }~,
    ~.micro-tick { position: relative; background: #f8fbfd; color: #425466; margin-top: 14px; }~,
    ~.micro-tick .mo { position: absolute; top: -14px; left: 50%; transform: translateX(-50%); font-size: 9px; color: #6b7b8c; white-space: nowrap; }~,
    ~.micro-cell { background: #ffffff; color: #0c4663; }~,
    ~.micro-cell.on { background: #0086ce; border-color: #0d66a1; color: #ffffff; font-weight: 700; }~,
    ~.micro-cell.sum-yes { background: #ed1c24; border-color: #c8161d; }~,
    ~.micro-cell.sum-no { background: #a8d08d; border-color: #86b36b; }~,
    ~.micro-cell.enc-c1 { background: #e0f0ff; border-color: #6ab0e8; }~,
    ~.micro-cell.enc-c2 { background: #d1e8ff; border-color: #509ee3; }~,
    ~.micro-cell.enc-c3 { background: #e8f4fd; border-color: #84badb; }~,
    ~.micro-cell.enc-c4 { background: #d9f0fa; border-color: #5bb2db; }~,
    ~.micro-track-links { display: flex; gap: 6px; flex-wrap: wrap; }~,
    ~.micro-orders { margin-top: 18px; }~,
    ~.micro-orders h3 { margin: 0 0 10px; font-size: 16px; }~,
    ~.search-preview { max-height: 140px; overflow: auto; white-space: pre-wrap; font-size: 12px; line-height: 1.4; }~,
    ~@keyframes spin { from { transform: rotate(0deg); } to { transform: rotate(360deg); } }~,
    ~</style>~,
    ~</head><body>~,
    ~<div class='nav-bar'>~,
    ~  <button class='nav-btn' data-module='ANVS' onclick="loadTab('ANVS')">GP Meds</button>~,
    ~  <button class='nav-btn' data-module='SEARCH' onclick="loadTab('SEARCH')">Search</button>~,
    ~  <button class='nav-btn' data-module='MICRO' onclick="loadTab('MICRO')">Antimicrobial</button>~,
    ~  <button class='nav-btn' data-module='NICU' onclick="loadTab('NICU')">NICU Labels</button>~,
    ~</div>~,
    ~<div id='app-status' class='status-banner' aria-live='polite'></div>~,
    ~<div id='app-root'></div>~,
    ~<script>~,
        ~var USER_ID = ~, $user_id, ~;~,
    ~var PATIENT_ID = ~, $pid, ~;~,
    ~var ENCNTR_ID = ~, $eid, ~;~,
    ~var TAB_CONFIG = {~,
    ~  ANVS:   { label: 'GP Meds',       program: '01_meds_pharm_anvs:group1' },~,
    ~  SEARCH: { label: 'Chart Search',  program: '01_meds_pharm_search:group1', params: function() { return '^MINE^,' + USER_ID + '.0,' + PATIENT_ID + '.0,' + ENCNTR_ID + '.0'; } },~,
    ~  MICRO:  { label: 'Antimicrobial', program: '01_meds_pharm_antimicrobial:group1', params: function() { return '^MINE^,' + PATIENT_ID + '.0,180'; } },~,
    ~  NICU:   { label: 'NICU Labels',   program: '01_meds_pharm_NICU_Inf:group1' }~,
    ~};~,
    ~function setStatus(message, tone) {~,
    ~  var node = document.getElementById('app-status');~,
    ~  node.className = tone ? 'status-banner ' + tone : 'status-banner';~,
    ~  node.textContent = message || '';~,
    ~}~,
    ~function escapeHtml(value) {~,
    ~  return String(value == null ? '' : value).replace(/&/g, '&amp;').replace(/</g, '&lt;').replace(/>/g, '&gt;').replace(/"/g, '&quot;').replace(/'/g, '&#39;');~,
    ~}~,
    ~function escapeAttr(value) { return escapeHtml(value); }~,
    ~function normalizeScan(value) { return String(value || '').replace(/[^A-Za-z0-9]/g, '').toUpperCase(); }~,
    ~function normalizePayload(payload) {~,
    ~  function lowerKeys(value) {~,
    ~    var key; var result;~,
    ~    if (value === null || value === undefined) { return value; }~,
    ~    if (Object.prototype.toString.call(value) === '[object Array]') { result = []; for (var i = 0; i < value.length; i++) { result.push(lowerKeys(value[i])); } return result; }~,
    ~    if (typeof value === 'object') { result = {}; for (key in value) { if (Object.prototype.hasOwnProperty.call(value, key)) { result[String(key).toLowerCase()] = lowerKeys(value[key]); } } return result; }~,
    ~    return value;~,
    ~  }~,
    ~  var normalized = lowerKeys(payload || {});~,
    ~  return normalized.reply || normalized;~,
    ~}~,
    ~function setActiveButton(module) {~,
    ~  var buttons = document.querySelectorAll('.nav-btn');~,
    ~  for (var i = 0; i < buttons.length; i++) { buttons[i].className = buttons[i].getAttribute('data-module') === module ? 'nav-btn active' : 'nav-btn'; }~,
    ~}~,
    ~function showLoading(label) {~,
    ~  document.getElementById('app-root').innerHTML = '<section class="panel"><div class="loading"><div class="loading-spinner"></div><div>Loading ' + escapeHtml(label) + '...</div></div></section>';~,
    ~}~,
    ~function configParams(program) {~,
    ~  for (var key in TAB_CONFIG) {~,
    ~    if (Object.prototype.hasOwnProperty.call(TAB_CONFIG, key) && TAB_CONFIG[key].program === program) {~,
    ~      if (typeof TAB_CONFIG[key].params === 'function') { return TAB_CONFIG[key].params(); }~,
    ~      break;~,
    ~    }~,
    ~  }~,
    ~  return '^MINE^,' + PATIENT_ID + '.0,' + ENCNTR_ID + '.0';~,
    ~}~,
    ~function callCCL(program) {~,
    ~  return new Promise(function(resolve, reject) {~,
    ~    if (!window.external || !window.external.XMLCclRequest) { reject(new Error('XMLCclRequest is unavailable.')); return; }~,
    ~    var xcr = window.external.XMLCclRequest();~,
    ~    xcr.open('GET', program, true);~,
    ~    xcr.onreadystatechange = function() {~,
    ~      if (xcr.readyState !== 4) { return; }~,
    ~      if (xcr.status !== 200) { reject(new Error('CCL request failed for ' + program + ' (' + xcr.status + ').')); return; }~,
    ~      var raw = xcr.responseText || '';~,
    ~      if (!raw) { reject(new Error(program + ' returned an empty response.')); return; }~,
    ~      try { resolve(normalizePayload(JSON.parse(raw))); } catch (error) { reject(new Error('Invalid JSON from ' + program + '.')); }~,
    ~    };~,
    ~    xcr.send(configParams(program));~,
    ~  });~,
    ~}~,
    ~function invokePrint(program, args, flags) {~,
    ~  try { if (typeof window.CCLLINK === 'function') { window.CCLLINK(program, args, Number(flags || 0)); return true; } if (window.external && typeof window.external.CCLLINK === 'function') { window.external.CCLLINK(program, args, Number(flags || 0)); return true; } } catch (error) {}~,
    ~  setStatus('Printing is unavailable in this context.', 'error');~,
    ~  return false;~,
    ~}~,
    ~function invokeAppLink(app, args) {~,
    ~  try { if (typeof window.APPLINK === 'function') { window.APPLINK(0, app, args); return true; } if (window.external && typeof window.external.APPLINK === 'function') { window.external.APPLINK(0, app, args); return true; } } catch (error) {}~,
    ~  setStatus('Chart navigation is unavailable in this context.', 'error');~,
    ~  return false;~,
    ~}~,
    ~function handleAppLink(button) { return invokeAppLink(button.getAttribute('data-app'), button.getAttribute('data-args')); }~,
    ~function handleNicuPrint(button) {~,
    ~  var expected = normalizeScan(button.getAttribute('data-expected-scan-code'));~,
    ~  var orderId = button.getAttribute('data-order-id');~,
    ~  if (expected) {~,
    ~    var input = document.getElementById('scan-' + orderId);~,
    ~    var actual = normalizeScan(input ? input.value : '');~,
    ~    if (!(actual === expected || actual.indexOf(expected) === 0)) { setStatus('Scan does not match the expected PN code.', 'error'); if (input) { input.value = ''; input.focus(); } return false; }~,
    ~  }~,
    ~  setStatus('');~,
    ~  return invokePrint(button.getAttribute('data-print-program'), button.getAttribute('data-print-args'), button.getAttribute('data-print-flags'));~,
    ~}~,
    ~function renderPlaceholder(data, target) {~,
    ~  var title = ((data.meta || {}).title) || 'Module Prototype';~,
    ~  var message = ((data.status || {}).message) || 'Backend migration is pending.';~,
    ~  target.innerHTML = '<section class="panel"><div class="panel-head"><div><h2>' + escapeHtml(title) + '</h2><p>Shell prototype active.</p></div><span class="pill">Stub</span></div><div class="panel-body"><div class="empty-state">' + escapeHtml(message) + '</div></div></section>';~,
    ~}~,
    ~function renderDebug(program, data, target) {~,
    ~  target.innerHTML = '<section class="panel"><div class="panel-head"><div><h2>' + escapeHtml(program) + '</h2><p>Debug JSON view</p></div></div><pre class="debug">' + escapeHtml(JSON.stringify(data, null, 2)) + '</pre></section>';~,
    ~}~,
    ~function renderAnvs(data, target) {~,
    ~  var meta = data.meta || {};~,
    ~  var items = data.medications || [];~,
    ~  var html = [];~,
    ~  html.push('<section class="panel"><div class="panel-head"><div><h2>' + escapeHtml(meta.title || 'GP Medications') + '</h2><p>JSON backend migrated from the working ANVS prototype.</p></div><span class="pill">' + items.length + '</span></div><div class="panel-body">');~,
    ~  html.push('<div class="summary-row"><div class="summary-card"><strong>Patient</strong><span>' + escapeHtml(meta.patient_id) + '</span></div><div class="summary-card"><strong>Encounter</strong><span>' + escapeHtml(meta.encntr_id) + '</span></div><div class="summary-card"><strong>Records</strong><span>' + escapeHtml(meta.total_records || items.length) + '</span></div></div>');~,
    ~  if (!items.length) { html.push('<div class="empty-state">' + escapeHtml(((data.status || {}).message) || 'No GP medication details found.') + '</div>'); } else { html.push('<div class="card-grid">'); for (var i = 0; i < items.length; i++) { html.push('<article class="doc-card"><h3>' + escapeHtml(items[i].dt_tm || '') + '</h3><div class="meta-line">' + escapeHtml(items[i].prsnl || '') + ' | Event ' + escapeHtml(items[i].event_id || '') + '</div><div class="note-text">' + escapeHtml(items[i].blob_text || '') + '</div></article>'); } html.push('</div>'); }~,
    ~  html.push('</div></section>');~,
    ~  target.innerHTML = html.join('');~,
    ~}~,
    ~function renderSearch(data, target) {~,
    ~  var meta = data.meta || {}; var summary = data.summary || {}; var results = data.results || []; var html = [];~,
    ~  html.push('<section class="panel"><div class="panel-head"><div><h2>' + escapeHtml(meta.title || 'Chart Search') + '</h2><p>Legacy note/blob search delivered through the SPA shell.</p></div><span class="pill">' + results.length + '</span></div><div class="panel-body">');~,
    ~  html.push('<div class="summary-row"><div class="summary-card"><strong>Patient</strong><span>' + escapeHtml(meta.patient_id) + '</span></div><div class="summary-card"><strong>Encounter</strong><span>' + escapeHtml(meta.encntr_id) + '</span></div><div class="summary-card"><strong>Results</strong><span>' + escapeHtml(summary.total_results || results.length) + '</span></div><div class="summary-card"><strong>Notes</strong><span>' + escapeHtml(summary.notes || 0) + '</span></div><div class="summary-card"><strong>Sticky</strong><span>' + escapeHtml(summary.sticky_notes || 0) + '</span></div></div>');~,
    ~  if (!results.length) { html.push('<div class="empty-state">' + escapeHtml(((data.status || {}).message) || 'No chart search results found.') + '</div>'); } else { html.push('<table class="data-grid"><thead><tr><th>Type</th><th>Title</th><th>Date/Time</th><th>Author</th><th>Preview</th></tr></thead><tbody>'); for (var i = 0; i < results.length; i++) { html.push('<tr><td>' + escapeHtml(results[i].category || results[i].source_type || '') + '</td><td><strong>' + escapeHtml(results[i].title || '') + '</strong></td><td>' + escapeHtml(results[i].event_dt_tm || '') + '</td><td>' + escapeHtml(results[i].authored_by || '') + '</td><td><div class="search-preview">' + escapeHtml(results[i].doc_text || '') + '</div></td></tr>'); } html.push('</tbody></table>'); }~,
    ~  target.innerHTML = html.join('') + '</div></section>';~,
    ~}~,
    ~function renderNicuInfusions(data, target) {~,
    ~  var meta = data.meta || {}; var items = data.infusions || []; var html = [];~,
    ~  html.push('<section class="panel"><div class="panel-head"><div><h2>' + escapeHtml(meta.title || 'NICU Infusions') + '</h2><p>Pure JavaScript render using NICU label-print metadata.</p></div><span class="pill">' + items.length + '</span></div><div class="panel-body">');~,
    ~  html.push('<div class="summary-row"><div class="summary-card"><strong>Patient</strong><span>' + escapeHtml(meta.patient_id) + '</span></div><div class="summary-card"><strong>Encounter</strong><span>' + escapeHtml(meta.encntr_id == null ? 'N/A' : meta.encntr_id) + '</span></div><div class="summary-card"><strong>Active Items</strong><span>' + items.length + '</span></div></div>');~,
    ~  if (!items.length) {~,
    ~    html.push('<div class="empty-state">' + escapeHtml(((data.status || {}).message) || 'No active infusions found.') + '</div>');~,
    ~  } else {~,
    ~    html.push('<table class="data-grid"><thead><tr><th>Start</th><th>Infusion</th><th>Type</th><th>Print</th></tr></thead><tbody>');~,
    ~    for (var i = 0; i < items.length; i++) {~,
    ~      var item = items[i];~,
    ~      var badgeStyle = 'background:' + escapeAttr(item.category_color || '#e8f3f8') + ' ';~,
    ~      html.push('<tr><td>' + escapeHtml(item.start_dt_tm || '') + '</td>');~,
    ~      html.push('<td><strong>' + escapeHtml(item.display_name || '') + '</strong><div class="print-hint">' + escapeHtml(item.ordered_as || '') + '</div></td>');~,
    ~      html.push('<td><span class="cat-badge" style="' + badgeStyle + '">' + escapeHtml(item.category_label || '') + '</span></td>');~,
    ~      html.push('<td>');~,
    ~      if (Number(item.requires_scan || 0) === 1) {~,
    ~        html.push('<input id="scan-' + escapeAttr(item.order_id) + '" class="scan-input" type="text" placeholder="Scan Code" />');~,
    ~      }~,
    ~      html.push(~,
    ~        '<button class="print-btn" data-order-id="' + escapeAttr(item.order_id) + '"' +~,
    ~        ' data-expected-scan-code="' + escapeAttr(item.expected_scan_code || '') + '"' +~,
    ~        ' data-print-program="' + escapeAttr(item.print_program || '') + '"' +~,
    ~        ' data-print-args="' + escapeAttr(item.print_args || '') + '"' +~,
    ~        ' data-print-flags="' + escapeAttr(item.print_flags || '0') + '"' +~,
    ~        ' onclick="handleNicuPrint(this)">' + escapeHtml(item.print_label || 'Print') + '</button>'~,
    ~      );~,
    ~      if (item.print_hint) {~,
    ~        html.push('<div class="print-hint">' + escapeHtml(item.print_hint) + '</div>');~,
    ~      }~,
    ~      html.push('</td></tr>');~,
    ~    }~,
    ~    html.push('</tbody></table>');~,
    ~  }~,
    ~  html.push('</div></section>'); target.innerHTML = html.join('');~,
    ~}~,
    ~function renderAntimicrobial(data, target) {~,
    ~  var meta = data.meta || {}; var headers = data.headers || []; var summaryDays = data.summary_days || []; var timeline = data.timeline || []; var tracks = data.encounter_tracks || []; var orders = data.order_details || []; var html = [];~,
    ~  html.push('<section class="panel"><div class="panel-head"><div><h2>' + escapeHtml(meta.title || 'Antimicrobial') + '</h2><p>Timeline and order detail view migrated from the working DOT prototype.</p></div><span class="pill">' + escapeHtml(meta.day_count || headers.length) + ' days</span></div><div class="panel-body">');~,
    ~  html.push('<div class="summary-row"><div class="summary-card"><strong>Patient</strong><span>' + escapeHtml(meta.patient_id) + '</span></div><div class="summary-card"><strong>MRN</strong><span>' + escapeHtml(meta.mrn || '') + '</span></div><div class="summary-card"><strong>Date Range</strong><span>' + escapeHtml((meta.begin_date || '') + (meta.end_date ? ' to ' + meta.end_date : '')) + '</span></div><div class="summary-card"><strong>Total DOT</strong><span>' + escapeHtml(meta.grand_total_dot || 0) + '</span></div><div class="summary-card"><strong>Admins</strong><span>' + escapeHtml((Number(meta.powerchart_admins || 0) + Number(meta.anesthesia_admins || 0))) + '</span></div></div>');~,
    ~  html.push('<div class="micro-meta">Admission: ' + escapeHtml(meta.admit_date || '') + ' LOS: ' + escapeHtml(meta.los_days || '') + ' days Lookback: ' + escapeHtml(meta.lookback_days || '') + ' days Window: ' + escapeHtml(meta.begin_date || '') + ' to ' + escapeHtml(meta.end_date || '') + '</div>');~,
    ~  if (!timeline.length) { html.push('<div class="empty-state">' + escapeHtml(((data.status || {}).message) || 'No antimicrobial orders found in the selected window.') + '</div>'); target.innerHTML = html.join('') + '</div></section>'; return; }~,
    ~  html.push('<div class="micro-scroll"><table class="micro-grid"><thead><tr><th>Medication</th><th>Doses</th><th>DOT</th><th>Date Range</th></tr></thead><tbody>');~,
    ~  for (var i = 0; i < timeline.length; i++) { var row = timeline[i]; html.push('<tr><td><strong>' + escapeHtml(row.medication_name || '') + '</strong></td><td>' + escapeHtml(row.doses_total || 0) + '</td><td>' + escapeHtml(row.dot_total || 0) + '</td><td><div class="micro-strip">'); for (var h = 0; h < headers.length; h++) { var header = headers[h]; var title = (header.day_label || '') + ' ' + (header.month_label || ''); var value = ''; if (row.day_cells && row.day_cells[h]) { value = row.day_cells[h].display_value || ''; } html.push('<span class="micro-cell' + (value ? ' on' : '') + '" title="' + escapeAttr(title) + '">' + escapeHtml(value) + '</span>'); } html.push('</div></td></tr>'); }~,
    ~  if (summaryDays.length) { html.push('<tr><td><strong>Antimicrobial Summary</strong></td><td></td><td>' + escapeHtml(meta.grand_total_dot || 0) + '</td><td><div class="micro-strip">'); for (var s = 0; s < summaryDays.length; s++) { html.push('<span class="micro-cell ' + (Number(summaryDays[s].has_antimicrobial || 0) === 1 ? 'sum-yes' : 'sum-no') + '" title="' + escapeAttr(summaryDays[s].day_label || '') + '"></span>'); } html.push('</div></td></tr>'); }~,
    ~  if (tracks.length) { html.push('<tr><td><strong>Encounter</strong></td><td></td><td></td><td>'); for (var t = 0; t < tracks.length; t++) { var encs = tracks[t].encounters || []; html.push('<div class="micro-track-links">'); for (var e = 0; e < encs.length; e++) { html.push('<button class="link-btn secondary" data-app="' + escapeAttr(encs[e].applink_app || 'Powerchart.exe') + '" data-args="' + escapeAttr(encs[e].applink_args || '') + '" onclick="handleAppLink(this)">' + escapeHtml(encs[e].fin || ('Encounter ' + (encs[e].encntr_id || ''))) + '</button>'); } html.push('</div>'); } html.push('</td></tr>'); }~,
    ~  html.push('</tbody></table></div>');~,
    ~  if (orders.length) {~,
    ~    html.push('<div class="micro-orders"><h3>Antimicrobial Order Details</h3><table class="data-grid"><thead><tr><th>Medication</th><th>Doses</th><th>DOT</th><th>Target Dose</th><th>Order Detail</th><th>Indication</th><th>Start Date</th><th>Latest Status</th><th>Status Date</th><th>Order ID</th><th>FIN</th></tr></thead><tbody>');~,
    ~    for (var o = 0; o < orders.length; o++) {~,
    ~      var ord = orders[o];~,
    ~      html.push('<tr><td>' + escapeHtml(ord.medication_name || '') + '</td><td>' + escapeHtml(ord.doses_total || 0) + '</td><td>' + escapeHtml(ord.dot_total || 0) + '</td><td>' + escapeHtml(ord.target_dose || '') + '</td><td>' + escapeHtml(ord.order_detail || '') + '</td><td>' + escapeHtml(ord.indication || '') + '</td><td>' + escapeHtml(ord.start_date || '') + '</td><td>' + escapeHtml(ord.status || '') + '</td><td>' + escapeHtml(ord.status_date || '') + '</td><td>' + escapeHtml(ord.order_id || '') + '</td><td>');~,
    ~      if (ord.applink_args) {~,
    ~        html.push(~,
    ~          '<button class="link-btn secondary" data-app="' + escapeAttr(ord.applink_app || 'Powerchart.exe') + '"' +~,
    ~          ' data-args="' + escapeAttr(ord.applink_args || '') + '"' +~,
    ~          ' onclick="handleAppLink(this)">' + escapeHtml(ord.fin || '') + '</button>'~,
    ~        );~,
    ~      } else {~,
    ~        html.push(escapeHtml(ord.fin || ''));~,
    ~      }~,
    ~      html.push('</td></tr>');~,
    ~    }~,
    ~    html.push('</tbody></table></div>');~,
    ~  }~,
    ~  target.innerHTML = html.join('') + '</div></section>';~,
    ~}~,
    ~function renderModule(program, data, target) {~,
    ~  var code = ((data.status || {}).code || '').toLowerCase();~,
    ~  if (code === 'prototype_pending') { renderPlaceholder(data, target); return; }~,
    ~  if (program === '01_meds_pharm_anvs:group1') { renderAnvs(data, target); return; }~,
    ~  if (program === '01_meds_pharm_search:group1') { renderSearch(data, target); return; }~,
    ~  if (program === '01_meds_pharm_antimicrobial:group1') { renderAntimicrobial(data, target); return; }~,
    ~  if (program === '01_meds_pharm_NICU_Inf:group1') { renderNicuInfusions(data, target); return; }~,
    ~  renderDebug(program, data, target);~,
    ~}~,
    ~function loadTab(module) {~,
    ~  var config = TAB_CONFIG[module];~,
    ~  if (!config) { return; }~,
    ~  setActiveButton(module);~,
    ~  setStatus('');~,
    ~  showLoading(config.label);~,
    ~  callCCL(config.program).then(function(data) { renderModule(config.program, data, document.getElementById('app-root')); }).catch(function(error) { setStatus(error.message || 'Unable to load module.', 'error'); renderDebug(config.program, { error: error.message || 'Unable to load module.' }, document.getElementById('app-root')); });~,
    ~}~,
    ~loadTab('NICU');~,
    ~</script>~,
    ~</body></html>~
)
END GO
