DROP PROGRAM 01_meds_pharm_mpage:group1 GO
CREATE PROGRAM 01_meds_pharm_mpage:group1
PROMPT "Output to File/Printer/MINE" = "MINE", "User Id" = 0, "Patient ID" = 0, "Encounter Id" = 0
WITH OUTDEV, user_id, pid, eid

SET _memory_reply_string = BUILD2(
    ~<!DOCTYPE html>~,
    ~<html><head>~,
    ~<meta charset='utf-8'/>~,
    ~<meta name='discern' content='XMLCCLREQUEST,APPLINK,CCLLINK'/>~,
    ~<title>Pharmacy SPA Prototype</title>~,
    ~<style>~,
    ~/* Shared shell and utility styles */~,
    ~*,*::before,*::after{box-sizing:border-box}~,
    ~body{margin:0;height:100vh;overflow:hidden;font-family:-apple-system,BlinkMacSystemFont,'Segoe UI',Arial,sans-serif;font-size:13px;background:#f4f5f7;color:#333;display:flex;flex-direction:column;}~,
    ~a{color:#005b8f;text-decoration:none}~,
    ~a:hover{text-decoration:underline}~,
    ~.nav-bar{display:flex;align-items:flex-end;background:#fff;border-bottom:2px solid #ddd;padding:0 8px;flex-shrink:0}~,
    ~.nav-btn{padding:8px 16px;margin-right:4px;cursor:pointer;background:transparent;border:none;border-bottom:3px solid transparent;color:#666;font-size:13px;font-family:inherit;white-space:nowrap;outline:none;position:relative;bottom:-2px}~,
    ~.nav-btn:hover{background:#f0f4f8;color:#333}~,
    ~.nav-btn.active{border-bottom:3px solid #006f99;color:#006f99;font-weight:600;background:#fff}~,
    ~.status-banner{display:none;padding:6px 10px;background:#fff;color:#777;font-size:12px;border-bottom:1px solid #ddd;flex-shrink:0}~,
    ~.status-banner.visible{display:block}~,
    ~.status-banner.error{color:#a12622;background:#fff5f5}~,
    ~.status-banner.info{color:#666}~,
    ~#app-root{flex:1;padding:12px;background:#f4f5f7;overflow:auto}~,
    ~.panel{background:#fff;border:0;box-shadow:none;overflow:hidden}~,
    ~.module-shell{width:100%;margin-right:auto}~,
    ~.panel-head{display:flex;justify-content:space-between;align-items:flex-start;padding:0 0 8px;border-bottom:0}~,
    ~.panel-head h2{margin:0;font-size:18px;color:#005b8f}~,
    ~.panel-head p{margin:4px 0 0;color:#555;font-size:12px}~,
    ~.panel-body{padding:0}~,
    ~.pill,.pill-num{display:inline-block;min-width:22px;padding:1px 8px;font-size:11px;line-height:16px;background:#eceef1;color:#555;border:1px solid #d2d6da;border-radius:999px;text-align:center}~,
    ~.sub{color:#444;margin:4px 0 12px;font-size:12px}~,
    ~.empty-state{padding:18px 10px;color:#666;font-style:italic}~,
    ~.error-state{padding:20px;background:#fff;border:1px solid #e4caca;color:#7f1d1d}~,
    ~.error-state h2{margin:0 0 6px;font-size:18px;color:#a12622}~,
    ~.error-state p{margin:0;line-height:1.5}~,
    ~.loading{display:flex;align-items:center;justify-content:center;gap:10px;min-height:180px;padding:28px 12px;color:#666;background:#fff;border:1px solid #ddd}~,
    ~.loading-spinner{width:18px;height:18px;border:3px solid #d7e6ef;border-top-color:#0c7aa6;border-radius:50%;animation:spin .9s linear infinite}~,
    ~table.data-grid,table.legacy-grid,table.chart-tbl,table.data-tbl,table.nicu-tbl{width:100%;border-collapse:collapse;border:1px solid #b5b5b5;background:#fff}~,
    ~table.data-grid th,table.data-grid td,table.legacy-grid th,table.legacy-grid td,table.chart-tbl th,table.chart-tbl td,table.data-tbl th,table.data-tbl td,table.nicu-tbl th,table.nicu-tbl td{padding:6px 8px;border:1px solid #d6d9dd;vertical-align:top;text-align:left;font-size:12px}~,
    ~table.data-grid th,table.legacy-grid th,table.chart-tbl th.label,table.data-tbl th,table.nicu-tbl th{background:#e7eaee;color:#2f3c4b;font-weight:600}~,
    ~table.data-grid tr.even td,table.legacy-grid tr.even td,table.data-tbl tr.even td{background:#fafbfc}~,
    ~.doc-block{border:1px solid #d6d9dd;background:#fff;margin-bottom:10px}~,
    ~.doc-head{padding:6px 8px;background:#eef3f7;border-bottom:1px solid #d6d9dd;color:#2f3c4b;font-weight:600}~,
    ~.doc-meta{padding:4px 8px;color:#666;font-size:11px;border-bottom:1px solid #eef1f4}~,
    ~.doc-text{padding:8px;white-space:pre-wrap;line-height:1.4}~,
    ~.search-preview{max-height:140px;overflow:auto;white-space:pre-wrap;line-height:1.35}~,
    ~.search-bar{display:flex;gap:8px;flex-wrap:wrap;align-items:center;margin:6px 0 10px}~,
    ~.filter-pill{display:inline-block;padding:3px 9px;border:1px solid #c9d2da;background:#f7f9fb;color:#4d5b67;border-radius:12px;font-size:11px}~,
    ~.hr-flag{display:inline-block;margin-right:4px;padding:1px 6px;background:#fff3cd;border:1px solid #e0c36f;border-radius:9px;color:#6a4a00;font-size:10px}~,
    ~.print-btn,.link-btn,.btn-link{display:inline-block;background:#fff;color:#333;border:1px solid #999;padding:4px 12px;text-decoration:none;font-weight:600;font-size:11px;cursor:pointer;vertical-align:middle}~,
    ~.print-btn:hover,.link-btn:hover,.btn-link:hover{background:#e6f7ff;border-color:#0066cc;text-decoration:none}~,
    ~.link-btn.secondary{background:#fff;color:#005b8f}~,
    ~.print-hint{margin-top:4px;color:#666;font-size:11px}~,
    ~.scan-input{width:92px;margin-right:6px;padding:4px;border:1px solid #999;font-family:'Courier New',monospace;font-size:11px}~,
    ~.debug{margin:0;padding:12px;background:#1e1e1e;color:#d4d4d4;overflow:auto;font-size:11px;font-family:monospace}~,
    ~/* Shared interactive helpers */~,
    ~.search-box{border:1px solid #ccc;border-radius:3px;padding:4px 8px;font-size:12px;outline:none;background:#fff}~,
    ~.search-box:focus{border-color:#006f99;box-shadow:0 0 0 2px rgba(0,111,153,.15)}~,
    ~.match-nav .nav-btn{background:#fff;border:1px solid #ccc;padding:5px 10px;cursor:pointer;font-size:12px;color:#333;border-radius:3px;white-space:nowrap;margin-right:0}~,
    ~.match-nav .nav-btn:hover{background:#e9ecef;color:#333}~,
    ~.match-nav .nav-btn:disabled{opacity:.4;cursor:default}~,
    ~mark{background:#ffc107;color:#000;border-radius:2px;padding:0 2px}~,
    ~@keyframes spin{from{transform:rotate(0deg)}to{transform:rotate(360deg)}}~,
    ~</style>~,
    ~<style id='module-style-slot'></style>~,
    ~</head><body>~,
    ~<div class='nav-bar'>~,
    ~  <button class='nav-btn' data-module='SEARCH' onclick="loadTab('SEARCH')">Chart Search</button>~,
    ~  <button class='nav-btn' data-module='ACUITY' onclick="loadTab('ACUITY')">Patient Acuity</button>~,
    ~  <button class='nav-btn' data-module='ANVS' onclick="loadTab('ANVS')">GP Meds</button>~,
    ~  <button class='nav-btn' data-module='MICRO' onclick="loadTab('MICRO')">Antimicrobial DOT</button>~,
    ~  <button class='nav-btn' data-module='NICU' onclick="loadTab('NICU')">NICU Labels</button>~,
    ~</div>~,
    ~<div id='app-status' class='status-banner' aria-live='polite'></div>~,
    ~<div id='app-root'><section class="panel"><div class="panel-body"><div class="empty-state">Select a tab to load a report.</div></div></section></div>~,
    ~<script>~,
    ~/* Bootstrap and shell config */~,
        ~var USER_ID = ~, $user_id, ~;~,
    ~var PATIENT_ID = ~, $pid, ~;~,
    ~var ENCNTR_ID = ~, $eid, ~;~,
    ~var ACTIVE_TAB_ID = '';~,
    ~var TAB_REGISTRY = {~,
    ~  SEARCH: { id: 'SEARCH', label: 'Chart Search', program: '01_meds_pharm_search:group1', buildParams: function() { return '^MINE^,' + USER_ID + '.0,' + PATIENT_ID + '.0,' + ENCNTR_ID + '.0'; }, mountId: 'app-root', initHook: initSearchTab, legacyRender: null },~,
    ~  ACUITY: { id: 'ACUITY', label: 'Patient Acuity', program: '01_meds_pharm_acuity:group1', buildParams: function() { return '^MINE^,' + PATIENT_ID + '.0,' + ENCNTR_ID + '.0'; }, mountId: 'app-root', initHook: initAcuityTab, legacyRender: null },~,
    ~  ANVS: { id: 'ANVS', label: 'GP Meds', program: '01_meds_pharm_anvs:group1', buildParams: function() { return '^MINE^,' + PATIENT_ID + '.0,' + ENCNTR_ID + '.0'; }, mountId: 'app-root', initHook: initAnvsTab, legacyRender: null },~,
    ~  MICRO: { id: 'MICRO', label: 'Antimicrobial DOT', program: '01_meds_pharm_antimicrobial:group1', buildParams: function() { return '^MINE^,' + PATIENT_ID + '.0,200'; }, mountId: 'app-root', initHook: initMicroTab, legacyRender: null },~,
    ~  NICU: { id: 'NICU', label: 'NICU Labels', program: '01_meds_pharm_NICU_Inf:group1', buildParams: function() { return '^MINE^,' + PATIENT_ID + '.0'; }, mountId: 'app-root', initHook: initNicuTab, legacyRender: null }~,
    ~};~,
    ~/* Shared shell helpers */~,
    ~function setStatus(message, tone) {~,
    ~  var node = document.getElementById('app-status');~,
    ~  var classes = ['status-banner'];~,
    ~  if (message) { classes.push('visible'); if (tone) { classes.push(tone); } }~,
    ~  node.className = classes.join(' ');~,
    ~  node.textContent = message || '';~,
    ~}~,
    ~function escapeHtml(value) {~,
    ~  return String(value == null ? '' : value).replace(/&/g, '&amp;').replace(/</g, '&lt;').replace(/>/g, '&gt;').replace(/"/g, '&quot;').replace(/'/g, '&#39;');~,
    ~}~,
    ~function escapeAttr(value) { return escapeHtml(value); }~,
    ~function normalizeScan(value) { return String(value || '').replace(/[^A-Za-z0-9]/g, '').toUpperCase(); }~,
    ~function normalizePayload(payload) {~,
    ~  function lowerKeys(value) {~,
    ~    var key; var result;~,
    ~    if (value === null || value === undefined) { return value; }~,
    ~    if (Object.prototype.toString.call(value) === '[object Array]') { result = []; for (var i = 0; i < value.length; i++) { result.push(lowerKeys(value[i])); } return result; }~,
    ~    if (typeof value === 'object') { result = {}; for (key in value) { if (Object.prototype.hasOwnProperty.call(value, key)) { result[String(key).toLowerCase()] = lowerKeys(value[key]); } } return result; }~,
    ~    return value;~,
    ~  }~,
    ~  var normalized = lowerKeys(payload || {});~,
    ~  return normalized.reply || normalized;~,
    ~}~,
    ~/* Shared medication parsing helpers */~,
    ~var SPA_STATE = { anvs: null, search: null, micro: null, nicu: null, acuity: null };~,
    ~var HIGH_RISK_GROUPS = [~,
    ~  { label: 'LMWH', terms: ['tinzaparin','enoxaparin','dalteparin','heparin','fragmin','innohep','clexane'] },~,
    ~  { label: 'ANTICOAG', terms: ['warfarin','apixaban','rivaroxaban','dabigatran','edoxaban','coumadin','xarelto','eliquis','pradaxa','lixiana'] },~,
    ~  { label: 'VALPROATE', terms: ['valproate','sodium valproate','valproic','epilim','depakote','convulex'] },~,
    ~  { label: 'TOPIRAMATE', terms: ['topiramate','topamax'] },~,
    ~  { label: 'AED', terms: ['levetiracetam','carbamazepine','phenytoin','lamotrigine','keppra','tegretol','epanutin','lamictal','phenobarbitone','phenobarbital'] },~,
    ~  { label: 'IMMUNOSUPP', terms: ['methotrexate','azathioprine','mycophenolate','ciclosporin','tacrolimus','sirolimus','everolimus','imurel','cellcept','neoral','prograf'] },~,
    ~  { label: 'LITHIUM', terms: ['lithium','priadel','liskonum'] },~,
    ~  { label: 'CLOZAPINE', terms: ['clozapine','clozaril','denzapine'] },~,
    ~  { label: 'ISOTRET', terms: ['isotretinoin','roaccutane','accutane'] },~,
    ~  { label: 'THALID', terms: ['thalidomide','lenalidomide','pomalidomide','revlimid','imnovid'] },~,
    ~  { label: 'AMIODARONE', terms: ['amiodarone','cordarone'] },~,
    ~  { label: 'DIGOXIN', terms: ['digoxin','lanoxin'] },~,
    ~  { label: 'INSULIN', terms: ['insulin','novorapid','lantus','humalog','levemir','tresiba','toujeo','apidra','humulin','mixtard','novomix'] }~,
    ~];~,
    ~var ANVS_SECTION_PATTERNS = [~,
    ~  { re: /prescribed med/i, key: 'prescribed', label: 'Prescribed Medications', cls: 'sec-prescribed' },~,
    ~  { re: /discontinued med/i, key: 'discontinued', label: 'Discontinued Medications', cls: 'sec-discontinued' },~,
    ~  { re: /vaccination/i, key: 'vaccination', label: 'Vaccination History', cls: 'sec-vaccination' }~,
    ~];~,
    ~var ANVS_DATE_RE = /^(\d{2}\/\d{2}\/\d{4})\s+(.+)$/;~,
    ~function parseLegacyDateTime(value) {~,
    ~  var text = String(value || '').trim();~,
    ~  var match = /^(\d{2})\/(\d{2})\/(\d{4})(?:\s+(\d{2}):(\d{2}))?$/.exec(text);~,
    ~  if (!match) { return null; }~,
    ~  return new Date(Number(match[3]), Number(match[2]) - 1, Number(match[1]), Number(match[4] || 0), Number(match[5] || 0), 0, 0);~,
    ~}~,
    ~function relativeDateLabel(value) {~,
    ~  var dt = parseLegacyDateTime(value);~,
    ~  if (!dt) { return ''; }~,
    ~  var now = new Date();~,
    ~  var diffDays = Math.floor((now.getTime() - dt.getTime()) / 86400000);~,
    ~  if (diffDays < 1) { return 'Today'; }~,
    ~  if (diffDays < 7) { return diffDays + ' day' + (diffDays === 1 ? '' : 's') + ' ago'; }~,
    ~  if (diffDays < 31) { var weeks = Math.floor(diffDays / 7); return weeks + ' week' + (weeks === 1 ? '' : 's') + ' ago'; }~,
    ~  if (diffDays < 365) { var months = Math.round(diffDays / 30.5); return months + ' month' + (months === 1 ? '' : 's') + ' ago'; }~,
    ~  var years = Math.floor(diffDays / 365.25);~,
    ~  var remMonths = Math.round((diffDays - (years * 365.25)) / 30.5);~,
    ~  return remMonths > 0 ? years + ' yr ' + remMonths + ' mo ago' : years + ' yr' + (years === 1 ? '' : 's') + ' ago';~,
    ~}~,
    ~function getHighRiskMatchesText(text) {~,
    ~  var lower = String(text || '').toLowerCase();~,
    ~  var hits = [];~,
    ~  for (var i = 0; i < HIGH_RISK_GROUPS.length; i++) {~,
    ~    for (var j = 0; j < HIGH_RISK_GROUPS[i].terms.length; j++) {~,
    ~      if (lower.indexOf(HIGH_RISK_GROUPS[i].terms[j]) >= 0) { hits.push(HIGH_RISK_GROUPS[i].label); break; }~,
    ~    }~,
    ~  }~,
    ~  return hits;~,
    ~}~,
    ~function highlightText(text, term) {~,
    ~  var safe = escapeHtml(text || '');~,
    ~  if (!term) { return safe; }~,
    ~  var search = String(term).replace(/[.*+?^${}()|[\]\\]/g, '\\$&');~,
    ~  return safe.replace(new RegExp('(' + search + ')', 'gi'), '<mark>$1</mark>');~,
    ~}~,
    ~function decodeTextEntities(value) {~,
    ~  return String(value || '').replace(/&amp;/g, '&').replace(/&lt;/g, '<').replace(/&gt;/g, '>').replace(/&quot;/g, '"').replace(/&#39;/g, "'");~,
    ~}~,
    ~function parseBlobSections(rawText) {~,
    ~  var lines = String(rawText || '').replace(/<br\s*\/?>/gi, '\n').replace(/<[^>]+>/g, '').replace(/\r\n/g, '\n').replace(/\r/g, '\n').split('\n');~,
    ~  var sections = [];~,
    ~  var current = null;~,
    ~  for (var i = 0; i < lines.length; i++) {~,
    ~    var line = decodeTextEntities(lines[i]).trim();~,
    ~    var isHeader = false;~,
    ~    if (!line) { continue; }~,
    ~    for (var s = 0; s < ANVS_SECTION_PATTERNS.length; s++) {~,
    ~      if (ANVS_SECTION_PATTERNS[s].re.test(line)) { if (current) { sections.push(current); } current = { key: ANVS_SECTION_PATTERNS[s].key, label: ANVS_SECTION_PATTERNS[s].label, cls: ANVS_SECTION_PATTERNS[s].cls, rows: [] }; isHeader = true; break; }~,
    ~    }~,
    ~    if (isHeader) { continue; }~,
    ~    if (!current) { current = { key: 'other', label: '', cls: 'sec-other', rows: [] }; }~,
    ~    var match = ANVS_DATE_RE.exec(line);~,
    ~    if (match) { current.rows.push({ date: match[1], text: match[2] }); } else { current.rows.push({ date: '', text: line }); }~,
    ~  }~,
    ~  if (current) { sections.push(current); }~,
    ~  return sections;~,
    ~}~,
    ~function extractDrugKey(text) {~,
    ~  var tokens = String(text || '').toLowerCase().replace(/[^a-z0-9 ]/g, ' ').trim().split(/\s+/);~,
    ~  var stopWords = ['mg','ml','mcg','ug','g','tablet','tablets','capsule','capsules','injection','solution','cream','ointment','patch','spray','inhaler','drops','puff','puffs','unit','units','iu'];~,
    ~  var key = [];~,
    ~  for (var i = 0; i < Math.min(tokens.length, 6); i++) {~,
    ~    if (!tokens[i]) { continue; }~,
    ~    if (/^\d/.test(tokens[i]) || stopWords.indexOf(tokens[i]) >= 0) { break; }~,
    ~    key.push(tokens[i]);~,
    ~    if (key.length >= 3) { break; }~,
    ~  }~,
    ~  return key.join(' ');~,
    ~}~,
    ~function diffAnvsItems(itemA, itemB) {~,
    ~  function getSectionRows(item, key) { for (var i = 0; i < item.sections.length; i++) { if (item.sections[i].key === key) { return item.sections[i].rows; } } return []; }~,
    ~  function normalizeRowText(text) { return String(text || '').replace(/\s+/g, ' ').trim().toLowerCase(); }~,
    ~  function diffSectionRows(rowsA, rowsB) {~,
    ~    var metaA = []; var metaB = []; var exactB = {}; var keyB = {}; var diffA = []; var diffB = [];~,
    ~    for (var a = 0; a < rowsA.length; a++) { metaA.push({ norm: normalizeRowText(rowsA[a].text), key: extractDrugKey(rowsA[a].text) || normalizeRowText(rowsA[a].text) }); }~,
    ~    for (var b = 0; b < rowsB.length; b++) { metaB.push({ norm: normalizeRowText(rowsB[b].text), key: extractDrugKey(rowsB[b].text) || normalizeRowText(rowsB[b].text) }); if (!exactB[metaB[b].norm]) { exactB[metaB[b].norm] = []; } exactB[metaB[b].norm].push(b); }~,
    ~    for (var x = 0; x < metaA.length; x++) { var exactMatches = exactB[metaA[x].norm]; if (exactMatches && exactMatches.length) { var exactIndex = exactMatches.shift(); diffA[x] = { type: 'unchanged' }; diffB[exactIndex] = { type: 'unchanged' }; } }~,
    ~    for (var y = 0; y < metaB.length; y++) { if (diffB[y]) { continue; } if (!keyB[metaB[y].key]) { keyB[metaB[y].key] = []; } keyB[metaB[y].key].push(y); }~,
    ~    for (var c = 0; c < metaA.length; c++) { if (diffA[c]) { continue; } var keyMatches = keyB[metaA[c].key]; if (keyMatches && keyMatches.length) { var keyIndex = keyMatches.shift(); diffA[c] = { type: 'changed' }; diffB[keyIndex] = { type: 'changed' }; } else { diffA[c] = { type: 'added' }; } }~,
    ~    for (var d = 0; d < metaB.length; d++) { if (!diffB[d]) { diffB[d] = { type: 'removed' }; } }~,
    ~    return { diffA: diffA, diffB: diffB };~,
    ~  }~,
    ~  var sectionKeys = {}; var diffABySection = {}; var diffBBySection = {};~,
    ~  for (var i = 0; i < itemA.sections.length; i++) { if (itemA.sections[i].key && itemA.sections[i].key !== 'other') { sectionKeys[itemA.sections[i].key] = 1; } }~,
    ~  for (var j = 0; j < itemB.sections.length; j++) { if (itemB.sections[j].key && itemB.sections[j].key !== 'other') { sectionKeys[itemB.sections[j].key] = 1; } }~,
    ~  for (var key in sectionKeys) { if (Object.prototype.hasOwnProperty.call(sectionKeys, key)) { var sectionDiff = diffSectionRows(getSectionRows(itemA, key), getSectionRows(itemB, key)); diffABySection[key] = sectionDiff.diffA; diffBBySection[key] = sectionDiff.diffB; } }~,
    ~  return { diffA: diffABySection, diffB: diffBBySection };~,
    ~}~,
    ~function matchesSearchRange(result, days) {~,
    ~  if (!days || Number(days) <= 0) { return true; }~,
    ~  var dt = parseLegacyDateTime(result.event_dt_tm || result.dt_tm || '');~,
    ~  if (!dt) { return false; }~,
    ~  return ((new Date()).getTime() - dt.getTime()) <= (Number(days) * 86400000);~,
    ~}~,
    ~function getFilteredSearchResults(state) {~,
    ~  var term = String(state.searchTerm || '').toLowerCase();~,
    ~  var filtered = [];~,
    ~  for (var i = 0; i < state.results.length; i++) {~,
    ~    var result = state.results[i];~,
    ~    if (state.categoryCode !== 'ALL' && String(result.category || '') !== state.categoryCode) { continue; }~,
    ~    if (!matchesSearchRange(result, state.rangeDays)) { continue; }~,
    ~    if (term) { var haystack = [result.title || '', result.doc_text || '', result.authored_by || '', result.category || ''].join(' ').toLowerCase(); if (haystack.indexOf(term) < 0) { continue; } }~,
    ~    filtered.push(result);~,
    ~  }~,
    ~  return filtered;~,
    ~}~,
    ~function setActiveButton(module) {~,
    ~  var buttons = document.querySelectorAll('.nav-btn');~,
    ~  for (var i = 0; i < buttons.length; i++) { buttons[i].className = buttons[i].getAttribute('data-module') === module ? 'nav-btn active' : 'nav-btn'; }~,
    ~}~,
    ~function showLoading(label, target) {~,
    ~  var mountTarget = target || document.getElementById('app-root');~,
    ~  if (mountTarget) { mountTarget.innerHTML = '<section class="panel"><div class="loading"><div class="loading-spinner"></div><div>Loading ' + escapeHtml(label) + '...</div></div></section>'; }~,
    ~}~,
    ~function renderShellError(label, message, target) {~,
    ~  var mountTarget = target || document.getElementById('app-root');~,
    ~  if (mountTarget) { mountTarget.innerHTML = '<section class="panel"><div class="error-state"><h2>' + escapeHtml(label || 'Unable to load module') + '</h2><p>' + escapeHtml(message || 'Unable to load module.') + '</p></div></section>'; }~,
    ~}~,
    ~function initAnvsTab(tabId, data, target) {~,
    ~  bindAnvsStaticControls(target);~,
    ~  hydrateAnvsState(data);~,
    ~}~,
    ~function initSearchTab(tabId, data, target) {~,
    ~  bindSearchStaticControls(target);~,
    ~  hydrateSearchState(data);~,
    ~}~,
    ~function initMicroTab(tabId, data, target) {~,
    ~  var previous = SPA_STATE.micro || {};~,
    ~  var selectedMedication = previous.target === target ? (previous.selectedMedication || '') : '';~,
    ~  var root = target ? target.querySelector('.module-micro') : null;~,
    ~  SPA_STATE.micro = { data: data, target: target, selectedMedication: selectedMedication };~,
    ~  bindMicroStaticControls(root);~,
    ~  bindMicroRowHover(root);~,
    ~  applyMicroMedicationFilter(root, selectedMedication);~,
    ~}~,
    ~function initNicuTab(tabId, data, target) {~,
    ~  SPA_STATE.nicu = { lastInputId: '' };~,
    ~  bindNicuStaticControls(target);~,
    ~}~,
    ~function initAcuityTab(tabId, data, target) {~,
    ~  SPA_STATE.acuity = { target: target, score: Number((((data || {}).acuity || {}).score) || 0) };~,
    ~  bindAcuityStaticControls(target);~,
    ~}~,
    ~function getTabConfig(tabId) { return TAB_REGISTRY[tabId] || null; }~,
    ~function getTabTarget(tabId) { var config = getTabConfig(tabId); return config ? document.getElementById(config.mountId || 'app-root') : null; }~,
    ~function buildTabParams(tabId) {~,
    ~  var config = getTabConfig(tabId);~,
    ~  if (config && typeof config.buildParams === 'function') { return config.buildParams(); }~,
    ~  return '^MINE^,' + PATIENT_ID + '.0,' + ENCNTR_ID + '.0';~,
    ~}~,
    ~function collectUiText(parts) {~,
    ~  var text = [];~,
    ~  if (!parts || !parts.length) { return ''; }~,
    ~  for (var i = 0; i < parts.length; i++) { if (parts[i] && parts[i].text) { text.push(String(parts[i].text)); } }~,
    ~  return text.join('');~,
    ~}~,
    ~function setModuleStyles(cssText) {~,
    ~  var slot = document.getElementById('module-style-slot');~,
    ~  if (slot) { slot.textContent = cssText || ''; }~,
    ~}~,
    ~function mountBackendUi(tabId, data, target) {~,
    ~  var config = getTabConfig(tabId);~,
    ~  var ui = data && data.ui ? data.ui : null;~,
    ~  var html = collectUiText(ui ? ui.html_parts : null);~,
    ~  var css = collectUiText(ui ? ui.css_parts : null);~,
    ~  var code = ((data.status || {}).code || '').toLowerCase();~,
    ~  setModuleStyles('');~,
    ~  if (html) {~,
    ~    target.innerHTML = html;~,
    ~    setModuleStyles(css);~,
    ~    if (config && typeof config.initHook === 'function') { config.initHook(tabId, data, target); }~,
    ~    return;~,
    ~  }~,
    ~  if (code === 'prototype_pending') { renderPlaceholder(data, target); return; }~,
    ~  renderShellError(config ? config.label : tabId, ((data.status || {}).message) || 'Module UI payload missing.', target);~,
    ~}~,
    ~function callCCL(tabId) {~,
    ~  var config = getTabConfig(tabId);~,
    ~  var program = config ? config.program : '';~,
    ~  return new Promise(function(resolve, reject) {~,
    ~    if (!config || !program) { reject(new Error('Unknown tab configuration.')); return; }~,
    ~    if (!window.external || !window.external.XMLCclRequest) { reject(new Error('XMLCclRequest is unavailable.')); return; }~,
    ~    var xcr = window.external.XMLCclRequest();~,
    ~    xcr.open('GET', program, true);~,
    ~    xcr.onreadystatechange = function() {~,
    ~      if (xcr.readyState !== 4) { return; }~,
    ~      if (xcr.status !== 200) { reject(new Error('CCL request failed for ' + program + ' (' + xcr.status + ').')); return; }~,
    ~      var raw = xcr.responseText || '';~,
    ~      if (!raw) { reject(new Error(program + ' returned an empty response.')); return; }~,
    ~      try { resolve(normalizePayload(JSON.parse(raw))); } catch (error) { reject(new Error('Invalid JSON from ' + program + '.')); }~,
    ~    };~,
    ~    xcr.send(buildTabParams(tabId));~,
    ~  });~,
    ~}~,
    ~function invokePrint(program, args, flags) {~,
    ~  try { if (typeof window.CCLLINK === 'function') { window.CCLLINK(program, args, Number(flags || 0)); return true; } if (window.external && typeof window.external.CCLLINK === 'function') { window.external.CCLLINK(program, args, Number(flags || 0)); return true; } } catch (error) {}~,
    ~  setStatus('Printing is unavailable in this context.', 'error');~,
    ~  return false;~,
    ~}~,
    ~function invokeAppLink(app, args) {~,
    ~  try { if (typeof window.APPLINK === 'function') { window.APPLINK(0, app, args); return true; } if (window.external && typeof window.external.APPLINK === 'function') { window.external.APPLINK(0, app, args); return true; } } catch (error) {}~,
    ~  setStatus('Chart navigation is unavailable in this context.', 'error');~,
    ~  return false;~,
    ~}~,
    ~function handleAppLink(button) { return invokeAppLink(button.getAttribute('data-app'), button.getAttribute('data-args')); }~,
    ~function focusNicuScan(input) {~,
    ~  if (input && input.value === 'Scan Code') { input.value = ''; input.style.color = '#000000'; input.style.fontStyle = 'normal'; }~,
    ~}~,
    ~function blurNicuScan(input) {~,
    ~  if (input && input.value === '') { input.value = 'Scan Code'; input.style.color = '#999999'; input.style.fontStyle = 'italic'; }~,
    ~}~,
    ~function showNicuErrorModal(inputId) {~,
    ~  if (!SPA_STATE.nicu) { SPA_STATE.nicu = { lastInputId: '' }; }~,
    ~  SPA_STATE.nicu.lastInputId = inputId || '';~,
    ~  var overlay = document.getElementById('nicu-modal-overlay');~,
    ~  var box = document.getElementById('nicu-modal-box');~,
    ~  var ok = document.getElementById('nicu-modal-ok');~,
    ~  if (overlay) { overlay.style.display = 'block'; }~,
    ~  if (box) { box.style.display = 'block'; }~,
    ~  if (ok) { ok.focus(); }~,
    ~}~,
    ~function closeNicuErrorModal() {~,
    ~  var overlay = document.getElementById('nicu-modal-overlay');~,
    ~  var box = document.getElementById('nicu-modal-box');~,
    ~  var inputId = SPA_STATE.nicu && SPA_STATE.nicu.lastInputId ? SPA_STATE.nicu.lastInputId : '';~,
    ~  if (overlay) { overlay.style.display = 'none'; }~,
    ~  if (box) { box.style.display = 'none'; }~,
    ~  if (inputId) {~,
    ~    var input = document.getElementById(inputId);~,
    ~    if (input) { input.value = ''; input.style.color = '#000000'; input.style.fontStyle = 'normal'; input.focus(); }~,
    ~  }~,
    ~}~,
    ~function handleNicuPrint(button) {~,
    ~  var expected = normalizeScan(button.getAttribute('data-expected-scan-code'));~,
    ~  var orderId = button.getAttribute('data-order-id');~,
    ~  if (expected) {~,
    ~    var inputId = 'scan-' + orderId;~,
    ~    var input = document.getElementById(inputId);~,
    ~    var actualRaw = '';~,
    ~    if (!input) { alert('Scan box not found.'); return false; }~,
    ~    actualRaw = input.value || '';~,
    ~    if (actualRaw === 'Scan Code') { actualRaw = ''; }~,
    ~    if (!(normalizeScan(actualRaw) === expected || normalizeScan(actualRaw).indexOf(expected) === 0)) { showNicuErrorModal(inputId); return false; }~,
    ~  }~,
    ~  setStatus('');~,
    ~  invokePrint(button.getAttribute('data-print-program'), button.getAttribute('data-print-args'), button.getAttribute('data-print-flags'));~,
    ~  return false;~,
    ~}~,
    ~function bindNicuStaticControls(target) {~,
    ~  var root = target ? target.querySelector('.module-nicu') : null;~,
    ~  if (!root || root.getAttribute('data-bound') === '1') { return; }~,
    ~  root.setAttribute('data-bound', '1');~,
    ~  root.addEventListener('click', function(event) {~,
    ~    var node = event.target;~,
    ~    while (node && node !== root) {~,
    ~      if (node.id === 'nicu-modal-ok') { event.preventDefault(); closeNicuErrorModal(); return; }~,
    ~      if (node.classList && node.classList.contains('print-btn')) { event.preventDefault(); handleNicuPrint(node); return; }~,
    ~      node = node.parentNode;~,
    ~    }~,
    ~  });~,
    ~  root.addEventListener('focusin', function(event) {~,
    ~    var node = event.target;~,
    ~    if (node && node.classList && node.classList.contains('scan-input')) { focusNicuScan(node); }~,
    ~  });~,
    ~  root.addEventListener('focusout', function(event) {~,
    ~    var node = event.target;~,
    ~    if (node && node.classList && node.classList.contains('scan-input')) { blurNicuScan(node); }~,
    ~  });~,
    ~}~,
    ~function bindAcuityStaticControls(target) {~,
    ~  var root = target ? target.querySelector('.module-acuity') : null;~,
    ~  if (!root || root.getAttribute('data-click-bound') === '1') { return; }~,
    ~  root.setAttribute('data-click-bound', '1');~,
    ~  root.addEventListener('click', function(event) {~,
    ~    var node = event.target;~,
    ~    while (node && node !== root) {~,
    ~      if (node.classList && node.classList.contains('trigger-header')) {~,
    ~        var triggerId = node.getAttribute('data-trigger-id');~,
    ~        var details = triggerId ? root.querySelector('#trig-det-' + triggerId) : null;~,
    ~        var icon = triggerId ? root.querySelector('#trig-icon-' + triggerId) : null;~,
    ~        var expanded = node.getAttribute('aria-expanded') === 'true';~,
    ~        event.preventDefault();~,
    ~        node.setAttribute('aria-expanded', expanded ? 'false' : 'true');~,
    ~        if (details) { details.hidden = expanded; }~,
    ~        if (icon) { icon.textContent = expanded ? '+' : '-'; }~,
    ~        return;~,
    ~      }~,
    ~      node = node.parentNode;~,
    ~    }~,
    ~  });~,
    ~}~,
    ~function renderPlaceholder(data, target) {~,
    ~  var title = ((data.meta || {}).title) || 'Module Prototype';~,
    ~  var message = ((data.status || {}).message) || 'Backend migration is pending.';~,
    ~  target.innerHTML = '<section class="panel"><div class="panel-head"><div><h2>' + escapeHtml(title) + '</h2><p>Shell prototype active.</p></div><span class="pill">Stub</span></div><div class="panel-body"><div class="empty-state">' + escapeHtml(message) + '</div></div></section>';~,
    ~}~,
    ~/* ANVS module */~,
    ~function buildAnvsState(data) {~,
    ~  var items = data.medications || [];~,
    ~  var state = { items: [], current: 1, diffMode: false, compareMode: false, compareSelected: [], searchTerm: '', searchTimer: 0, scrollLockUntil: 0 };~,
    ~  for (var i = 0; i < items.length; i++) { state.items.push({ index: i + 1, event_id: items[i].event_id, dt_tm: items[i].dt_tm || '', prsnl: items[i].prsnl || '', blob_text: items[i].blob_text || '', sections: parseBlobSections(items[i].blob_text || ''), highRisk: getHighRiskMatchesText(items[i].blob_text || '') }); }~,
    ~  return state;~,
    ~}~,
    ~function bindAnvsStaticControls(target) {~,
    ~  var prev = target ? target.querySelector('#btn-prev') : null;~,
    ~  var next = target ? target.querySelector('#btn-next') : null;~,
    ~  var diff = target ? target.querySelector('#btn-diff') : null;~,
    ~  var compare = target ? target.querySelector('#btn-compare') : null;~,
    ~  var search = target ? target.querySelector('#anvs-search-box') : null;~,
    ~  if (prev && prev.getAttribute('data-bound') !== '1') { prev.setAttribute('data-bound', '1'); prev.addEventListener('click', prevAnvsBlob); }~,
    ~  if (next && next.getAttribute('data-bound') !== '1') { next.setAttribute('data-bound', '1'); next.addEventListener('click', nextAnvsBlob); }~,
    ~  if (diff && diff.getAttribute('data-bound') !== '1') { diff.setAttribute('data-bound', '1'); diff.addEventListener('click', toggleAnvsDiff); }~,
    ~  if (compare && compare.getAttribute('data-bound') !== '1') { compare.setAttribute('data-bound', '1'); compare.addEventListener('click', toggleAnvsCompare); }~,
    ~  if (search && search.getAttribute('data-bound') !== '1') { search.setAttribute('data-bound', '1'); search.addEventListener('input', function() { onAnvsSearchInput(this.value); }); }~,
    ~}~,
    ~function hydrateAnvsState(data) {~,
    ~  SPA_STATE.anvs = buildAnvsState(data);~,
    ~  refreshAnvsUI();~,
    ~  bindAnvsScrollSpy();~,
    ~}~,
    ~function buildAnvsNavHtml(state) {~,
    ~  var html = [];~,
    ~  if (!state.items.length) { return '<div class="gp-nav-item" style="color:#888;">No records found</div>'; }~,
    ~  for (var i = 0; i < state.items.length; i++) {~,
    ~    var item = state.items[i];~,
    ~    var classes = ['gp-nav-item'];~,
    ~    var matchCount = 0;~,
    ~    var flags = [];~,
    ~    if (item.index === state.current) { classes.push('active-nav'); }~,
    ~    if (state.compareSelected.indexOf(item.index) >= 0) { classes.push('compare-sel'); flags.push('<span class="nav-flag nav-flag-compare">COMPARE</span>'); }~,
    ~    for (var s = 0; s < item.sections.length; s++) { for (var r = 0; r < item.sections[s].rows.length; r++) { if (state.searchTerm && item.sections[s].rows[r].text.toLowerCase().indexOf(state.searchTerm) >= 0) { matchCount = matchCount + 1; } } }~,
    ~    for (var h = 0; h < item.highRisk.length; h++) { flags.push('<span class="nav-flag nav-flag-highrisk">' + escapeHtml(item.highRisk[h]) + '</span>'); }~,
    ~    if (matchCount > 0) { flags.push('<span class="nav-flag nav-flag-search">MATCH</span>'); }~,
    ~    html.push('<div id="nav-' + item.index + '" class="' + classes.join(' ') + '" onclick="handleAnvsNavClick(' + item.index + ')"><span class="nav-date">' + escapeHtml(item.dt_tm || '') + '</span><span class="nav-rel">' + escapeHtml(relativeDateLabel(item.dt_tm || '')) + '</span>' + (flags.length ? '<div class="nav-flags">' + flags.join('') + '</div>' : '') + '</div>');~,
    ~  }~,
    ~  return html.join('');~,
    ~}~,
    ~function renderAnvsSectionHtml(item, term, diffRows) {~,
    ~  var html = [];~,
    ~  if (!item.sections.length) { return '<em style="color:#aaa">No content</em>'; }~,
    ~  for (var s = 0; s < item.sections.length; s++) {~,
    ~    var section = item.sections[s];~,
    ~    html.push('<div class="med-section">');~,
    ~    if (section.label) { html.push('<div class="med-section-heading ' + escapeHtml(section.cls || 'sec-other') + '">' + escapeHtml(section.label) + '</div>'); }~,
    ~    if (!section.rows.length) { html.push('<div class="med-section-empty">None recorded</div>'); }~,
    ~    for (var r = 0; r < section.rows.length; r++) {~,
    ~      var row = section.rows[r];~,
    ~      var sectionDiffRows = diffRows && section.key ? diffRows[section.key] : null;~,
    ~      var diffInfo = sectionDiffRows && sectionDiffRows[r] ? sectionDiffRows[r] : null;~,
    ~      var classes = ['med-row'];~,
    ~      if (!row.date) { classes.push('non-dated'); }~,
    ~      if (diffInfo && diffInfo.type && diffInfo.type !== 'unchanged') { classes.push('diff-' + diffInfo.type); }~,
    ~      if (term && row.text.toLowerCase().indexOf(term) >= 0) { classes.push('search-hit'); }~,
    ~      html.push('<div class="' + classes.join(' ') + '" data-medtext="' + escapeAttr(row.text || '') + '">');~,
    ~      if (row.date) { html.push('<span class="med-date">' + escapeHtml(row.date) + '</span>'); }~,
    ~      html.push('<span class="med-text">' + highlightText(row.text || '', term));~,
    ~      var hits = getHighRiskMatchesText(row.text || '');~,
    ~      for (var h = 0; h < hits.length; h++) { html.push('<span class="highrisk-pill">' + escapeHtml(hits[h]) + '</span>'); }~,
    ~      html.push('</span>');~,
    ~      if (diffInfo && diffInfo.type && diffInfo.type !== 'unchanged') { html.push('<span class="diff-tag diff-tag-' + diffInfo.type + '">' + escapeHtml(diffInfo.type.toUpperCase()) + '</span>'); }~,
    ~      html.push('</div>');~,
    ~    }~,
    ~    html.push('</div>');~,
    ~  }~,
    ~  return html.join('');~,
    ~}~,
    ~function buildAnvsListHtml(state) {~,
    ~  var html = [];~,
    ~  for (var i = 0; i < state.items.length; i++) {~,
    ~    var item = state.items[i];~,
    ~    var diffRows = null;~,
    ~    if (state.diffMode && i < state.items.length - 1) { diffRows = diffAnvsItems(item, state.items[i + 1]).diffA; }~,
    ~    html.push('<div id="blob-' + item.index + '" class="blob-record" data-idx="' + item.index + '"><div class="blob-meta">Performed: <span id="blob-meta-text-' + item.index + '">' + escapeHtml(item.dt_tm || '') + ' by ' + escapeHtml(item.prsnl || '') + '</span></div><div id="blob-body-' + item.index + '">' + renderAnvsSectionHtml(item, state.searchTerm, diffRows) + '</div></div>');~,
    ~  }~,
    ~  if (!state.items.length) { html.push('<p style="color:#666;font-style:italic;padding:20px;">No GP Medication Details available for this patient.</p>'); }~,
    ~  return html.join('');~,
    ~}~,
    ~function updateAnvsControls(state) {~,
    ~  var counter = document.getElementById('anvs-counter');~,
    ~  if (counter) { counter.textContent = state.items.length ? (state.current + ' of ' + state.items.length) : '0 of 0'; }~,
    ~  var prev = document.getElementById('btn-prev'); var next = document.getElementById('btn-next');~,
    ~  if (prev) { prev.disabled = state.current <= 1; }~,
    ~  if (next) { next.disabled = state.current >= state.items.length; }~,
    ~  var diff = document.getElementById('btn-diff'); var compare = document.getElementById('btn-compare');~,
    ~  if (diff) { diff.className = state.diffMode ? 'tool-btn active' : 'tool-btn'; }~,
    ~  if (compare) { compare.className = state.compareMode ? 'tool-btn active' : 'tool-btn'; compare.textContent = state.compareMode ? 'Exit Compare' : 'Compare'; }~,
    ~  var info = document.getElementById('anvs-search-info');~,
    ~  if (info) { var matches = 0; var recordMatches = 0; for (var i = 0; i < state.items.length; i++) { var itemMatched = false; for (var s = 0; s < state.items[i].sections.length; s++) { for (var r = 0; r < state.items[i].sections[s].rows.length; r++) {~,
    ~    if (state.searchTerm && state.items[i].sections[s].rows[r].text.toLowerCase().indexOf(state.searchTerm) >= 0) { matches = matches + 1; itemMatched = true; } } } if (itemMatched) { recordMatches = recordMatches + 1; } }~,
    ~    info.textContent = state.searchTerm ? (matches + ' match' + (matches === 1 ? '' : 'es') + ' in ' + recordMatches + ' record' + (recordMatches === 1 ? '' : 's')) : ''; }~,
    ~}~,
    ~function refreshAnvsCompareView(state) {~,
    ~  var pane = document.getElementById('anvs-compare-pane'); var scrollMain = document.getElementById('anvs-scroll-main'); var banner = document.getElementById('compare-banner');~,
    ~  if (!pane || !scrollMain || !banner) { return; }~,
    ~  if (state.compareMode && state.compareSelected.length === 2) {~,
    ~    var itemA = state.items[state.compareSelected[0] - 1]; var itemB = state.items[state.compareSelected[1] - 1]; var diff = diffAnvsItems(itemA, itemB);~,
    ~    scrollMain.style.display = 'none'; pane.className = 'compare-pane visible'; banner.className = 'compare-banner visible';~,
    ~    banner.innerHTML = 'Comparing records ' + state.compareSelected[0] + ' and ' + state.compareSelected[1] + ' <button class="tool-btn" onclick="exitAnvsCompareView()">Exit Compare</button>';~,
    ~    document.getElementById('compare-header-a').textContent = itemA.dt_tm + ' by ' + itemA.prsnl;~,
    ~    document.getElementById('compare-header-b').textContent = itemB.dt_tm + ' by ' + itemB.prsnl;~,
    ~    document.getElementById('compare-col-a').innerHTML = renderAnvsSectionHtml(itemA, state.searchTerm, diff.diffA);~,
    ~    document.getElementById('compare-col-b').innerHTML = renderAnvsSectionHtml(itemB, state.searchTerm, diff.diffB);~,
    ~  } else {~,
    ~    scrollMain.style.display = ''; pane.className = 'compare-pane'; banner.className = state.compareMode && state.compareSelected.length === 1 ? 'compare-banner visible' : 'compare-banner'; banner.textContent = state.compareMode && state.compareSelected.length === 1 ? 'Compare mode: 1 selected - click another record' : '';~,
    ~  }~,
    ~}~,
    ~function refreshAnvsNav(state) { var nav = document.getElementById('anvs-nav'); if (nav) { nav.innerHTML = buildAnvsNavHtml(state); } }~,
    ~function refreshAnvsUI() {~,
    ~  var state = SPA_STATE.anvs; if (!state) { return; }~,
    ~  refreshAnvsNav(state);~,
    ~  var scrollMain = document.getElementById('anvs-scroll-main'); if (scrollMain) { scrollMain.innerHTML = buildAnvsListHtml(state); }~,
    ~  updateAnvsControls(state); refreshAnvsCompareView(state);~,
    ~}~,
    ~function bindAnvsScrollSpy() {~,
    ~  var scroller = document.getElementById('anvs-scroll-main');~,
    ~  if (!scroller || scroller.getAttribute('data-bound') === '1') { return; }~,
    ~  scroller.setAttribute('data-bound', '1');~,
    ~  scroller.addEventListener('scroll', function() { var state = SPA_STATE.anvs; if (!state || state.compareMode || Date.now() < Number(state.scrollLockUntil || 0)) { return; } var cards = scroller.querySelectorAll('.blob-record'); var nextCurrent = state.current; for (var i = 0; i < cards.length; i++) { if ((cards[i].offsetTop - scroller.scrollTop) <= 40) { nextCurrent = Number(cards[i].getAttribute('data-idx')); } } if (nextCurrent !== state.current) { state.current = nextCurrent; refreshAnvsNav(state); updateAnvsControls(state); } });~,
    ~}~,
    ~function handleAnvsNavClick(index) {~,
    ~  var state = SPA_STATE.anvs; if (!state) { return; }~,
    ~  if (state.compareMode) { if (state.compareSelected.indexOf(index) >= 0) { state.compareSelected.splice(state.compareSelected.indexOf(index), 1); } else if (state.compareSelected.length < 2) { state.compareSelected.push(index); } refreshAnvsNav(state); updateAnvsControls(state); refreshAnvsCompareView(state); return; }~,
    ~  state.current = index; state.scrollLockUntil = Date.now() + 450; refreshAnvsNav(state); updateAnvsControls(state);~,
    ~  var card = document.getElementById('blob-' + index); var scroller = document.getElementById('anvs-scroll-main');~,
    ~  var anchor = card ? (card.querySelector('.blob-meta') || card) : null;~,
    ~  if (anchor && scroller) { var targetTop = scroller.scrollTop + anchor.getBoundingClientRect().top - scroller.getBoundingClientRect().top - 8; scroller.scrollTo({ top: Math.max(0, targetTop), behavior: 'smooth' }); }~,
    ~}~,
    ~function prevAnvsBlob() { var state = SPA_STATE.anvs; if (state && state.current > 1) { handleAnvsNavClick(state.current - 1); } }~,
    ~function nextAnvsBlob() { var state = SPA_STATE.anvs; if (state && state.current < state.items.length) { handleAnvsNavClick(state.current + 1); } }~,
    ~function toggleAnvsDiff() { var state = SPA_STATE.anvs; if (!state) { return; } state.diffMode = !state.diffMode; refreshAnvsUI(); }~,
    ~function toggleAnvsCompare() { var state = SPA_STATE.anvs; if (!state) { return; } state.compareMode = !state.compareMode; state.compareSelected = []; refreshAnvsUI(); }~,
    ~function exitAnvsCompareView() { var state = SPA_STATE.anvs; if (!state) { return; } state.compareMode = false; state.compareSelected = []; refreshAnvsUI(); }~,
    ~function onAnvsSearchInput(value) {~,
    ~  var state = SPA_STATE.anvs; if (!state) { return; }~,
    ~  clearTimeout(state.searchTimer);~,
    ~  state.searchTimer = setTimeout(function() { state.searchTerm = String(value || '').toLowerCase(); refreshAnvsUI(); if (state.searchTerm) { for (var i = 0; i < state.items.length; i++) { var matched = false; for (var s = 0; s < state.items[i].sections.length; s++) { for (var r = 0; r < state.items[i].sections[s].rows.length; r++) { if (state.items[i].sections[s].rows[r].text.toLowerCase().indexOf(state.searchTerm) >= 0) { matched = true; break; } } if (matched) { break; } } if (matched) { handleAnvsNavClick(state.items[i].index); break; } } } }, 250);~,
    ~}~,
    ~/* Search module */~,
    ~function buildSearchState(data) {~,
    ~  return { results: data.results || [], filters: data.filters || [], categoryCode: 'ALL', rangeDays: 0, searchTerm: '', selectedResultIndex: 0, matchIndex: 0, inputTimer: 0 };~,
    ~}~,
    ~function bindSearchStaticControls(target) {~,
    ~  var input = target ? target.querySelector('#search-filter-input') : null;~,
    ~  var clearBtn = target ? target.querySelector('#search-clear-btn') : null;~,
    ~  var range = target ? target.querySelector('#search-range-select') : null;~,
    ~  var prev = target ? target.querySelector('#search-match-prev') : null;~,
    ~  var next = target ? target.querySelector('#search-match-next') : null;~,
    ~  if (input && input.getAttribute('data-bound') !== '1') { input.setAttribute('data-bound', '1'); input.addEventListener('input', function() { onSearchFilterInput(this.value); }); }~,
    ~  if (clearBtn && clearBtn.getAttribute('data-bound') !== '1') { clearBtn.setAttribute('data-bound', '1'); clearBtn.addEventListener('click', clearSearchTerm); }~,
    ~  if (range && range.getAttribute('data-bound') !== '1') { range.setAttribute('data-bound', '1'); range.addEventListener('change', function() { setSearchRange(this.value); }); }~,
    ~  if (prev && prev.getAttribute('data-bound') !== '1') { prev.setAttribute('data-bound', '1'); prev.addEventListener('click', function() { stepSearchMatch(-1); }); }~,
    ~  if (next && next.getAttribute('data-bound') !== '1') { next.setAttribute('data-bound', '1'); next.addEventListener('click', function() { stepSearchMatch(1); }); }~,
    ~}~,
    ~function hydrateSearchState(data) {~,
    ~  SPA_STATE.search = buildSearchState(data);~,
    ~  var input = document.getElementById('search-filter-input');~,
    ~  if (input) { input.placeholder = 'Search ' + SPA_STATE.search.results.length + ' chart documents...'; input.value = SPA_STATE.search.searchTerm || ''; }~,
    ~  refreshSearchUI();~,
    ~}~,
    ~function getSearchFilterCount(state, filter) {~,
    ~  var count = 0;~,
    ~  for (var i = 0; i < state.results.length; i++) { if (filter.filter_type === 'category') { if (filter.code === 'ALL' || String(state.results[i].category || '') === filter.code) { count = count + 1; } } else if (filter.filter_type === 'date_range') { if (matchesSearchRange(state.results[i], filter.days || 0)) { count = count + 1; } } }~,
    ~  return count;~,
    ~}~,
    ~function buildSearchFilterHtml(state, filterType) {~,
    ~  var html = [];~,
    ~  for (var i = 0; i < state.filters.length; i++) {~,
    ~    var filter = state.filters[i];~,
    ~    if (filter.filter_type !== filterType) { continue; }~,
    ~    var isActive = filterType === 'category' ? state.categoryCode === filter.code : Number(state.rangeDays || 0) === Number(filter.days || 0);~,
    ~    var action = filterType === 'category' ? ('setSearchCategory(' + JSON.stringify(String(filter.code || '')).replace(/"/g, '&quot;') + ')') : ('setSearchRange(' + Number(filter.days || 0) + ')');~,
    ~    html.push('<button class="filter-pill' + (isActive ? ' active' : '') + '" onclick="' + action + '">' + escapeHtml(filter.label || filter.code || '') + '</button>');~,
    ~  }~,
    ~  return html.join('');~,
    ~}~,
    ~function buildSearchDateOptionsHtml(state) {~,
    ~  var html = [];~,
    ~  for (var i = 0; i < state.filters.length; i++) {~,
    ~    var filter = state.filters[i];~,
    ~    if (filter.filter_type !== 'date_range') { continue; }~,
    ~    var selected = Number(state.rangeDays || 0) === Number(filter.days || 0) ? ' selected' : '';~,
    ~    html.push('<option value="' + Number(filter.days || 0) + '"' + selected + '>' + escapeHtml(filter.label || 'All Time') + '</option>');~,
    ~  }~,
    ~  return html.join('');~,
    ~}~,
    ~function getSearchPreviewText(text) {~,
    ~  return decodeTextEntities(String(text || '').replace(/<br\s*\/?>/gi, ' ').replace(/<[^>]+>/g, ' ')).replace(/\s+/g, ' ').trim();~,
    ~}~,
    ~function highlightSearchDocHtml(text, term) {~,
    ~  var html = String(text || '');~,
    ~  if (!term) { return html; }~,
    ~  var search = String(term).replace(/[.*+?^${}()|[\]\\]/g, '\\$&');~,
    ~  return html.replace(new RegExp('(' + search + ')', 'gi'), '<mark>$1</mark>');~,
    ~}~,
    ~function buildSearchSidebarHtml(state, filtered) {~,
    ~  if (!filtered.length) { return '<div class="search-empty">No documents match the current filters.</div>'; }~,
    ~  var html = [];~,
    ~  for (var i = 0; i < filtered.length; i++) {~,
    ~    var result = filtered[i];~,
    ~    var active = result.result_index === state.selectedResultIndex ? ' active' : '';~,
    ~    var previewText = getSearchPreviewText(result.doc_text || '');~,
    ~    var flags = [];~,
    ~    if (result.high_risk_labels) { var labels = String(result.high_risk_labels).split(','); for (var h = 0; h < labels.length; h++) { if (labels[h]) { flags.push('<span class="hr-flag">' + escapeHtml(labels[h]) + '</span>'); } } }~,
    ~    html.push('<div class="doc-item' + active + '" onclick="selectSearchResult(' + result.result_index + ')"><div class="doc-meta">' + escapeHtml(result.event_dt_tm || '') + ' | ' + escapeHtml(result.authored_by || '') + '</div>' +~,
    ~      '<div class="doc-title"><span class="type-badge">' + escapeHtml(result.source_type || result.category || 'DOC') + '</span><span class="raw-title">' + highlightText(result.title || '', state.searchTerm) + '</span></div>' +~,
    ~      (flags.length ? '<div class="nav-flags">' + flags.join('') + '</div>' : '') + '<div class="doc-preview">' + highlightText(previewText.substring(0, 260), state.searchTerm) + '</div></div>');~,
    ~  }~,
    ~  return html.join('');~,
    ~}~,
    ~function buildSearchViewerHtml(state, filtered) {~,
    ~  if (!filtered.length) { return '<div class="search-empty">No chart documents match the current filters.</div>'; }~,
    ~  if (!Number(state.selectedResultIndex || 0)) { return '<div class="search-empty">Select a document or type to search.</div>'; }~,
    ~  var current = null;~,
    ~  for (var i = 0; i < filtered.length; i++) { if (filtered[i].result_index === state.selectedResultIndex) { current = filtered[i]; break; } }~,
    ~  if (!current) { return '<div class="search-empty">Select a document or type to search.</div>'; }~,
    ~  var flags = [];~,
    ~  if (current.high_risk_labels) { var labels = String(current.high_risk_labels).split(','); for (var h = 0; h < labels.length; h++) { if (labels[h]) { flags.push('<span class="hr-flag">' + escapeHtml(labels[h]) + '</span>'); } } }~,
    ~  return '<div class="search-doc-header"><h3 class="search-doc-title">' + escapeHtml(current.title || '') + '</h3><div class="search-doc-meta"><span class="type-badge">' + escapeHtml(current.source_type || current.category || 'DOC') + '</span>' +~,
    ~    '<b>Date/Time:</b> ' + escapeHtml(current.event_dt_tm || '') + ' &nbsp; <b>Author:</b> ' + escapeHtml(current.authored_by || '') + (flags.length ? ' &nbsp; ' + flags.join('') : '') + '</div></div>' +~,
    ~    '<div class="search-doc-body">' + highlightSearchDocHtml(current.doc_text || '', state.searchTerm) + '</div>';~,
    ~}~,
    ~function highlightActiveSearchMatch() {~,
    ~  var state = SPA_STATE.search; var viewer = document.getElementById('search-document-viewer'); if (!state || !viewer) { return; }~,
    ~  var matches = viewer.querySelectorAll('mark');~,
    ~  for (var i = 0; i < matches.length; i++) { matches[i].classList.remove('active-match'); }~,
    ~  if (!matches.length) { return; }~,
    ~  if (state.matchIndex < 0 || state.matchIndex >= matches.length) { state.matchIndex = 0; }~,
    ~  matches[state.matchIndex].classList.add('active-match');~,
    ~  matches[state.matchIndex].scrollIntoView({ behavior: 'smooth', block: 'center' });~,
    ~  document.getElementById('search-match-index').textContent = state.matchIndex + 1;~,
    ~}~,
    ~function syncSearchMatchNav() {~,
    ~  var state = SPA_STATE.search; var viewer = document.getElementById('search-document-viewer'); var nav = document.getElementById('search-match-nav'); if (!state || !viewer || !nav) { return; }~,
    ~  var matches = viewer.querySelectorAll('mark');~,
    ~  if (!matches.length) { state.matchIndex = -1; nav.style.display = 'none'; document.getElementById('search-match-total').textContent = '0'; document.getElementById('search-match-index').textContent = '0'; return; }~,
    ~  if (state.matchIndex < 0 || state.matchIndex >= matches.length) { state.matchIndex = 0; }~,
    ~  nav.style.display = 'flex';~,
    ~  document.getElementById('search-match-total').textContent = matches.length;~,
    ~  highlightActiveSearchMatch();~,
    ~}~,
    ~function refreshSearchUI() {~,
    ~  var state = SPA_STATE.search; if (!state) { return; }~,
    ~  var filtered = getFilteredSearchResults(state);~,
    ~  if (!filtered.length) { state.selectedResultIndex = 0; state.matchIndex = 0; } else { var found = false; for (var i = 0; i < filtered.length; i++) { if (filtered[i].result_index === state.selectedResultIndex) { found = true; break; } } if (!found) { state.selectedResultIndex = 0; state.matchIndex = 0; } }~,
    ~  document.getElementById('search-category-filters').innerHTML = buildSearchFilterHtml(state, 'category');~,
    ~  document.getElementById('search-range-select').innerHTML = buildSearchDateOptionsHtml(state);~,
    ~  document.getElementById('search-results-sidebar').innerHTML = buildSearchSidebarHtml(state, filtered);~,
    ~  document.getElementById('search-document-viewer').innerHTML = buildSearchViewerHtml(state, filtered);~,
    ~  document.getElementById('search-visible-count').textContent = filtered.length + ' displayed';~,
    ~  document.getElementById('search-clear-btn').className = 'clear-btn' + (state.searchTerm ? ' visible' : '');~,
    ~  syncSearchMatchNav();~,
    ~}~,
    ~function setSearchCategory(code) { var state = SPA_STATE.search; if (!state) { return; } state.categoryCode = code; state.matchIndex = 0; refreshSearchUI(); }~,
    ~function setSearchRange(days) { var state = SPA_STATE.search; if (!state) { return; } state.rangeDays = Number(days || 0); state.matchIndex = 0; refreshSearchUI(); }~,
    ~function selectSearchResult(index) { var state = SPA_STATE.search; if (!state) { return; } state.selectedResultIndex = Number(index || 0); state.matchIndex = 0; refreshSearchUI(); }~,
    ~function stepSearchMatch(direction) { var state = SPA_STATE.search; var viewer = document.getElementById('search-document-viewer'); var matches = viewer ? viewer.querySelectorAll('mark') : []; if (!state || !matches.length) { return; } state.matchIndex = (state.matchIndex + direction + matches.length) % matches.length; highlightActiveSearchMatch(); }~,
    ~function clearSearchTerm() { var input = document.getElementById('search-filter-input'); var state = SPA_STATE.search; if (!input || !state) { return; } input.value = ''; state.searchTerm = ''; state.matchIndex = 0; refreshSearchUI(); input.focus(); }~,
    ~function onSearchFilterInput(value) { var state = SPA_STATE.search; if (!state) { return; } clearTimeout(state.inputTimer); state.inputTimer = setTimeout(function() { state.searchTerm = String(value || '').toLowerCase(); state.matchIndex = 0; refreshSearchUI(); }, 200); }~,
    ~/* NICU module */~,
    ~/* Antimicrobial module */~,
    ~function getMicroRoot(node) {~,
      ~  while (node && node.nodeType === 1) {~,
      ~    if (node.classList && node.classList.contains('module-micro')) { return node; }~,
    ~    node = node.parentNode;~,
    ~  }~,
    ~  return null;~,
    ~}~,
    ~function bindMicroStaticControls(root) {~,
    ~  if (!root || root.getAttribute('data-click-bound') === '1') { return; }~,
    ~  root.setAttribute('data-click-bound', '1');~,
    ~  root.addEventListener('click', function(event) {~,
    ~    var node = event.target;~,
    ~    while (node && node !== root) {~,
    ~      if (node.getAttribute && node.getAttribute('data-app')) { event.preventDefault(); handleAppLink(node); return; }~,
    ~      if (node.classList && node.classList.contains('med-trigger')) { toggleMicroMedication(node); return; }~,
    ~      node = node.parentNode;~,
    ~    }~,
    ~  });~,
    ~}~,
    ~function applyMicroMedicationFilter(root, medicationName) {~,
    ~  if (!root) { return; }~,
    ~  var items = root.querySelectorAll('.dimmable');~,
    ~  var triggers = root.querySelectorAll('.med-trigger');~,
    ~  var selected = String(medicationName || '');~,
    ~  var active = '';~,
    ~  var i;~,
    ~  for (i = 0; i < triggers.length; i++) {~,
    ~    if (triggers[i].getAttribute('data-med') === selected) {~,
    ~      triggers[i].classList.add('active-filter');~,
    ~      active = selected;~,
    ~    } else {~,
    ~      triggers[i].classList.remove('active-filter');~,
    ~    }~,
    ~  }~,
    ~  if (!active) {~,
    ~    for (i = 0; i < items.length; i++) { items[i].classList.remove('dimmed'); }~,
    ~  } else {~,
    ~    for (i = 0; i < items.length; i++) {~,
    ~      if (items[i].getAttribute('data-med') === active || items[i].classList.contains('always-on')) {~,
    ~        items[i].classList.remove('dimmed');~,
    ~      } else {~,
    ~        items[i].classList.add('dimmed');~,
    ~      }~,
    ~    }~,
    ~  }~,
    ~  if (SPA_STATE.micro) { SPA_STATE.micro.selectedMedication = active; }~,
    ~}~,
    ~function toggleMicroMedication(trigger) {~,
    ~  if (!trigger) { return; }~,
    ~  var root = getMicroRoot(trigger);~,
    ~  var medName = trigger.getAttribute('data-med') || '';~,
    ~  var isCurrentlyActive = trigger.classList.contains('active-filter');~,
    ~  applyMicroMedicationFilter(root, isCurrentlyActive ? '' : medName);~,
    ~}~,
    ~function bindMicroRowHover(root) {~,
    ~  if (!root) { return; }~,
    ~  var items = root.querySelectorAll('.dimmable[data-med]');~,
    ~  for (var i = 0; i < items.length; i++) {~,
    ~    items[i].addEventListener('mouseenter', function() {~,
    ~      var med = this.getAttribute('data-med');~,
    ~      var siblings;~,
    ~      var j;~,
    ~      if (!med) { return; }~,
    ~      siblings = root.querySelectorAll('.dimmable[data-med]');~,
    ~      for (j = 0; j < siblings.length; j++) { if (siblings[j].getAttribute('data-med') === med) { siblings[j].classList.add('row-hover'); } }~,
    ~    });~,
    ~    items[i].addEventListener('mouseleave', function() {~,
    ~      var med = this.getAttribute('data-med');~,
    ~      var siblings;~,
    ~      var j;~,
    ~      if (!med) { return; }~,
    ~      siblings = root.querySelectorAll('.dimmable[data-med]');~,
    ~      for (j = 0; j < siblings.length; j++) { if (siblings[j].getAttribute('data-med') === med) { siblings[j].classList.remove('row-hover'); } }~,
    ~    });~,
    ~  }~,
    ~}~,
    ~/* Tab lifecycle and bootstrap */~,
    ~function loadTab(tabId) {~,
    ~  var config = getTabConfig(tabId);~,
    ~  var target = getTabTarget(tabId);~,
    ~  if (!config || !target) { return; }~,
    ~  ACTIVE_TAB_ID = tabId;~,
    ~  setActiveButton(ACTIVE_TAB_ID);~,
    ~  setStatus('');~,
    ~  showLoading(config.label, target);~,
    ~  callCCL(tabId).then(function(data) { mountBackendUi(tabId, data, target); }).catch(function(error) { setStatus(error.message || 'Unable to load module.', 'error'); renderShellError(config.label, error.message || 'Unable to load module.', target); });~,
    ~}~,
    ~</script>~,
    ~</body></html>~
)
END GO






