DROP PROGRAM 01_meds_pharm_mpage:group1 GO
CREATE PROGRAM 01_meds_pharm_mpage:group1
PROMPT "Output to File/Printer/MINE" = "MINE", "PatientID" = 0, "EncntrID" = 0
WITH OUTDEV, pid, eid

SET _memory_reply_string = BUILD2(
    ~<!DOCTYPE html>~,
    ~<html><head>~,
    ~<meta charset='utf-8'/>~,
    ~<meta name='discern' content='XMLCCLREQUEST,APPLINK,CCLLINK'/>~,
    ~<title>Pharmacy SPA Prototype</title>~,
    ~<style>~,
    ~  * { box-sizing: border-box; }~,
    ~  body { margin: 0; min-height: 100vh; font-family: Segoe UI, Arial, sans-serif; background: #f4f7fa; color: #1c2733; display: flex; flex-direction: column; }~,
    ~  .nav-bar { display: flex; gap: 4px; padding: 10px 12px 0; background: linear-gradient(135deg, #0c4663 0%, #155e75 100%); }~,
    ~  .nav-btn { border: 0; border-radius: 10px 10px 0 0; padding: 12px 18px; background: transparent; color: #cfe4ec; cursor: pointer; font-size: 13px; font-weight: 600; }~,
    ~  .nav-btn:hover { color: #ffffff; background: rgba(255,255,255,0.08); }~,
    ~  .nav-btn.active { background: #f4f7fa; color: #0c4663; }~,
    ~  .status-banner { min-height: 22px; padding: 10px 16px 0; font-size: 13px; }~,
    ~  .status-banner.error { color: #a12622; }~,
    ~  .status-banner.info { color: #155e75; }~,
    ~  #app-root { flex: 1; padding: 16px; }~,
    ~  .panel { background: #ffffff; border: 1px solid #d9e2ec; border-radius: 14px; box-shadow: 0 8px 24px rgba(18, 38, 63, 0.08); overflow: hidden; }~,
    ~  .panel-head { display: flex; justify-content: space-between; align-items: center; gap: 16px; padding: 18px 20px; border-bottom: 1px solid #e6edf3; }~,
    ~  .panel-head h2 { margin: 0 0 4px; font-size: 20px; }~,
    ~  .panel-head p { margin: 0; color: #5d6b79; }~,
    ~  .pill { display: inline-flex; align-items: center; justify-content: center; min-width: 52px; padding: 8px 12px; border-radius: 999px; background: #e8f3f8; color: #0c4663; font-size: 12px; font-weight: 700; }~,
    ~  .panel-body { padding: 20px; }~,
    ~  .empty-state { padding: 28px; text-align: center; color: #5d6b79; }~,
    ~  .loading { display: flex; align-items: center; gap: 12px; padding: 24px; }~,
    ~  .loading-spinner { width: 28px; height: 28px; border: 4px solid #d7e6ef; border-top-color: #0c7aa6; border-radius: 50%; animation: spin 0.9s linear infinite; }~,
    ~  .summary-row { display: flex; gap: 12px; flex-wrap: wrap; margin-bottom: 16px; }~,
    ~  .summary-card { min-width: 150px; padding: 14px 16px; border: 1px solid #d9e2ec; border-radius: 12px; background: #f8fbfd; }~,
    ~  .summary-card strong { display: block; font-size: 12px; color: #5d6b79; margin-bottom: 6px; text-transform: uppercase; letter-spacing: 0.04em; }~,
    ~  .summary-card span { font-size: 18px; font-weight: 700; color: #1c2733; }~,
    ~  table.data-grid { width: 100%; border-collapse: collapse; }~,
    ~  table.data-grid th, table.data-grid td { padding: 12px 14px; border-bottom: 1px solid #e6edf3; vertical-align: top; text-align: left; }~,
    ~  table.data-grid th { font-size: 12px; text-transform: uppercase; letter-spacing: 0.04em; color: #5d6b79; background: #f8fbfd; }~,
    ~  table.data-grid tr:last-child td { border-bottom: 0; }~,
    ~  .cat-cell { width: 110px; }~,
    ~  .cat-badge { display: inline-flex; align-items: center; justify-content: center; min-width: 74px; padding: 6px 10px; border-radius: 999px; font-size: 12px; font-weight: 700; color: #14303f; }~,
    ~  .print-cell { width: 260px; }~,
    ~  .scan-input { width: 120px; margin-right: 8px; padding: 8px 10px; border: 1px solid #b7c6d3; border-radius: 8px; font-size: 12px; }~,
    ~  .print-btn { padding: 9px 12px; border: 1px solid #0c7aa6; border-radius: 8px; background: #0c7aa6; color: #ffffff; cursor: pointer; font-weight: 600; }~,
    ~  .print-btn.secondary { background: #ffffff; color: #0c7aa6; }~,
    ~  .print-hint { margin-top: 6px; font-size: 12px; color: #5d6b79; }~,
    ~  .debug { margin: 0; padding: 20px; background: #0f1720; color: #d5dde5; overflow: auto; font-size: 12px; }~,
    ~  @keyframes spin { from { transform: rotate(0deg); } to { transform: rotate(360deg); } }~,
    ~  @media (max-width: 900px) { .panel-head { flex-direction: column; align-items: flex-start; } .print-cell { width: auto; } .scan-input { display: block; width: 100%; margin: 0 0 8px; } table.data-grid, table.data-grid thead, table.data-grid tbody, table.data-grid th, table.data-grid td, table.data-grid tr { display: block; } table.data-grid thead { display: none; } table.data-grid tr { padding: 12px 0; border-bottom: 1px solid #e6edf3; } table.data-grid td { border: 0; padding: 6px 0; } }~,
    ~</style>~,
    ~</head><body>~,
    ~<div class='nav-bar'>~,
    ~  <button class='nav-btn' data-module='ANVS' onclick="loadTab('ANVS')">GP Meds</button>~,
    ~  <button class='nav-btn' data-module='SEARCH' onclick="loadTab('SEARCH')">Search</button>~,
    ~  <button class='nav-btn' data-module='MICRO' onclick="loadTab('MICRO')">Antimicrobial</button>~,
    ~  <button class='nav-btn' data-module='NICU' onclick="loadTab('NICU')">NICU Labels</button>~,
    ~</div>~,
    ~<div id='app-status' class='status-banner' aria-live='polite'></div>~,
    ~<div id='app-root'></div>~,
    ~<script>~,
    ~var PATIENT_ID = ~, $pid, ~;~,
    ~var ENCNTR_ID = ~, $eid, ~;~,
    ~var TAB_CONFIG = {~,
    ~  ANVS:   { label: 'GP Meds',       program: '01_meds_pharm_anvs:group1' },~,
    ~  SEARCH: { label: 'Chart Search',  program: '01_meds_pharm_search:group1' },~,
    ~  MICRO:  { label: 'Antimicrobial', program: '01_meds_pharm_antimicrobial:group1' },~,
    ~  NICU:   { label: 'NICU Labels',   program: '01_meds_pharm_NICU_Inf:group1' }~,
    ~};~,
    ~function setStatus(message, tone) {~,
    ~  var node = document.getElementById('app-status');~,
    ~  node.className = tone ? 'status-banner ' + tone : 'status-banner';~,
    ~  node.textContent = message || '';~,
    ~}~,
    ~function escapeHtml(value) {~,
    ~  return String(value == null ? '' : value)~,
    ~    .replace(/&/g, '&amp;')~,
    ~    .replace(/</g, '&lt;')~,
    ~    .replace(/>/g, '&gt;')~,
    ~    .replace(/"/g, '&quot;')~,
    ~    .replace(/'/g, '&#39;');~,
    ~}~,
    ~function escapeAttr(value) {~,
    ~  return escapeHtml(value);~,
    ~}~,
    ~function normalizeScan(value) {~,
    ~  return String(value || '').replace(/[^A-Za-z0-9]/g, '').toUpperCase();~,
    ~}~,
    ~function normalizePayload(payload) {~,
    ~  function lowerKeys(value) {~,
    ~    var key;~,
    ~    var result;~,
    ~    if (value === null || value === undefined) { return value; }~,
    ~    if (Object.prototype.toString.call(value) === '[object Array]') {~,
    ~      result = [];~,
    ~      for (var i = 0; i < value.length; i++) { result.push(lowerKeys(value[i])); }~,
    ~      return result;~,
    ~    }~,
    ~    if (typeof value === 'object') {~,
    ~      result = {};~,
    ~      for (key in value) {~,
    ~        if (Object.prototype.hasOwnProperty.call(value, key)) {~,
    ~          result[String(key).toLowerCase()] = lowerKeys(value[key]);~,
    ~        }~,
    ~      }~,
    ~      return result;~,
    ~    }~,
    ~    return value;~,
    ~  }~,
    ~  var normalized = lowerKeys(payload || {});~,
    ~  return normalized.reply || normalized;~,
    ~}~,
    ~function setActiveButton(module) {~,
    ~  var buttons = document.querySelectorAll('.nav-btn');~,
    ~  for (var i = 0; i < buttons.length; i++) {~,
    ~    buttons[i].className = buttons[i].getAttribute('data-module') === module ? 'nav-btn active' : 'nav-btn';~,
    ~  }~,
    ~}~,
    ~function showLoading(label) {~,
    ~  document.getElementById('app-root').innerHTML = '<section class="panel"><div class="loading"><div class="loading-spinner"></div><div>Loading ' + escapeHtml(label) + '...</div></div></section>';~,
    ~}~,
    ~function callCCL(program) {~,
    ~  return new Promise(function(resolve, reject) {~,
    ~    if (!window.external || !window.external.XMLCclRequest) {~,
    ~      reject(new Error('XMLCclRequest is unavailable.'));~,
    ~      return;~,
    ~    }~,
    ~    var xcr = window.external.XMLCclRequest();~,
    ~    xcr.open('GET', program, true);~,
    ~    xcr.onreadystatechange = function() {~,
    ~      if (xcr.readyState !== 4) { return; }~,
    ~      if (xcr.status !== 200) {~,
    ~        reject(new Error('CCL request failed for ' + program + ' (' + xcr.status + ').'));~,
    ~        return;~,
    ~      }~,
    ~      var raw = xcr.responseText || '';~,
    ~      if (!raw) {~,
    ~        reject(new Error(program + ' returned an empty response.'));~,
    ~        return;~,
    ~      }~,
    ~      try {~,
    ~        resolve(normalizePayload(JSON.parse(raw)));~,
    ~      } catch (error) {~,
    ~        reject(new Error('Invalid JSON from ' + program + '.'));~,
    ~      }~,
    ~    };~,
    ~    xcr.send('^MINE^, ' + PATIENT_ID + ', ' + ENCNTR_ID);~,
    ~  });~,
    ~}~,
    ~function invokePrint(program, args, flags) {~,
    ~  try {~,
    ~    if (typeof window.CCLLINK === 'function') {~,
    ~      window.CCLLINK(program, args, Number(flags || 0));~,
    ~      return true;~,
    ~    }~,
    ~    if (window.external && typeof window.external.CCLLINK === 'function') {~,
    ~      window.external.CCLLINK(program, args, Number(flags || 0));~,
    ~      return true;~,
    ~    }~,
    ~  } catch (error) {~,
    ~  }~,
    ~  setStatus('Printing is unavailable in this context.', 'error');~,
    ~  return false;~,
    ~}~,
    ~function handleNicuPrint(button) {~,
    ~  var expected = normalizeScan(button.getAttribute('data-expected-scan-code'));~,
    ~  var orderId = button.getAttribute('data-order-id');~,
    ~  if (expected) {~,
    ~    var input = document.getElementById('scan-' + orderId);~,
    ~    var actual = normalizeScan(input ? input.value : '');~,
    ~    if (!(actual === expected || actual.indexOf(expected) === 0)) {~,
    ~      setStatus('Scan does not match the expected PN code.', 'error');~,
    ~      if (input) { input.value = ''; input.focus(); }~,
    ~      return false;~,
    ~    }~,
    ~  }~,
    ~  setStatus('');~,
    ~  return invokePrint(button.getAttribute('data-print-program'), button.getAttribute('data-print-args'), button.getAttribute('data-print-flags'));~,
    ~}~,
    ~function renderPlaceholder(data, target) {~,
    ~  var title = ((data.meta || {}).title) || 'Module Prototype';~,
    ~  var message = ((data.status || {}).message) || 'Backend migration is pending.';~,
    ~  target.innerHTML = '<section class="panel"><div class="panel-head"><div><h2>' + escapeHtml(title) + '</h2><p>Shell prototype active.</p></div><span class="pill">Stub</span></div><div class="panel-body"><div class="empty-state">' + escapeHtml(message) + '</div></div></section>';~,
    ~}~,
    ~function renderDebug(program, data, target) {~,
    ~  target.innerHTML = '<section class="panel"><div class="panel-head"><div><h2>' + escapeHtml(program) + '</h2><p>Debug JSON view</p></div></div><pre class="debug">' + escapeHtml(JSON.stringify(data, null, 2)) + '</pre></section>';~,
    ~}~,
    ~function renderNicuInfusions(data, target) {~,
    ~  var meta = data.meta || {};~,
    ~  var items = data.infusions || [];~,
    ~  var html = [];~,
    ~  html.push('<section class="panel">');~,
    ~  html.push('<div class="panel-head"><div><h2>' + escapeHtml(meta.title || 'NICU Infusions') + '</h2><p>Pure JavaScript render using NICU label-print metadata.</p></div><span class="pill">' + items.length + '</span></div>');~,
    ~  html.push('<div class="panel-body">');~,
    ~  html.push('<div class="summary-row">');~,
    ~  html.push('<div class="summary-card"><strong>Patient</strong><span>' + escapeHtml(meta.patient_id) + '</span></div>');~,
    ~  html.push('<div class="summary-card"><strong>Encounter</strong><span>' + escapeHtml(meta.encntr_id == null ? 'N/A' : meta.encntr_id) + '</span></div>');~,
    ~  html.push('<div class="summary-card"><strong>Active Items</strong><span>' + items.length + '</span></div>');~,
    ~  html.push('</div>');~,
    ~  if (!items.length) {~,
    ~    html.push('<div class="empty-state">' + escapeHtml(((data.status || {}).message) || 'No active infusions found.') + '</div>');~,
    ~  } else {~,
    ~    html.push('<table class="data-grid"><thead><tr><th>Start</th><th>Infusion</th><th class="cat-cell">Type</th><th class="print-cell">Print</th></tr></thead><tbody>');~,
    ~    for (var i = 0; i < items.length; i++) {~,
    ~      var item = items[i];~,
    ~      var badgeStyle = 'background:' + escapeAttr(item.category_color || '#e8f3f8') + ';';~,
    ~      html.push('<tr>');~,
    ~      html.push('<td>' + escapeHtml(item.start_dt_tm || '') + '</td>');~,
    ~      html.push('<td><strong>' + escapeHtml(item.display_name || '') + '</strong><div class="print-hint">' + escapeHtml(item.ordered_as || '') + '</div></td>');~,
    ~      html.push('<td class="cat-cell"><span class="cat-badge" style="' + badgeStyle + '">' + escapeHtml(item.category_label || '') + '</span></td>');~,
    ~      html.push('<td class="print-cell">');~,
    ~      if (Number(item.requires_scan || 0) === 1) {~,
    ~        html.push('<input id="scan-' + escapeAttr(item.order_id) + '" class="scan-input" type="text" placeholder="Scan Code" />');~,
    ~      }~,
    ~      html.push('<button class="print-btn' + (Number(item.requires_scan || 0) === 1 ? ' secondary' : '') + '" data-order-id="' + escapeAttr(item.order_id) + '" data-print-program="' + escapeAttr(item.print_program || '') + '" data-print-args="' + escapeAttr(item.print_args || '') + '" data-print-flags="' + escapeAttr(item.print_flags || 0) + '" data-expected-scan-code="' + escapeAttr(item.expected_scan_code || '') + '" onclick="return handleNicuPrint(this);">' + escapeHtml(item.print_label || 'Print Label') + '</button>');~,
    ~      if (item.expected_scan_code) {~,
    ~        html.push('<div class="print-hint">Scan verification required.</div>');~,
    ~      }~,
    ~      html.push('</td>');~,
    ~      html.push('</tr>');~,
    ~    }~,
    ~    html.push('</tbody></table>');~,
    ~  }~,
    ~  html.push('</div></section>');~,
    ~  target.innerHTML = html.join('');~,
    ~}~,
    ~function renderModule(program, data, target) {~,
    ~  if (data && data.status && data.status.code === 'prototype_pending') {~,
    ~    renderPlaceholder(data, target);~,
    ~    return;~,
    ~  }~,
    ~  if (program === '01_meds_pharm_NICU_Inf:group1') {~,
    ~    renderNicuInfusions(data, target);~,
    ~    return;~,
    ~  }~,
    ~  renderDebug(program, data, target);~,
    ~}~,
    ~function loadTab(module) {~,
    ~  var config = TAB_CONFIG[module];~,
    ~  if (!config) { return; }~,
    ~  setActiveButton(module);~,
    ~  setStatus('');~,
    ~  showLoading(config.label);~,
    ~  callCCL(config.program)~,
    ~    .then(function(data) { renderModule(config.program, data, document.getElementById('app-root')); })~,
    ~    .catch(function(error) {~,
    ~      setStatus(error.message || 'Unable to load module.', 'error');~,
    ~      renderDebug(config.program, { error: error.message || 'Unable to load module.' }, document.getElementById('app-root'));~,
    ~    });~,
    ~}~,
    ~loadTab('NICU');~,
    ~</script>~,
    ~</body></html>~
)
END GO


